-- Blank Space v75 Supabase update
-- Run this in Supabase SQL Editor before testing v75.
-- Adds profile pictures, public leaderboard points, username changes every 7 days,
-- admin point awards for suggestions, and the storage bucket for public avatars.
-- It is safe to run more than once.

-- Keep/repair v74 public policies and friends table for anyone who skipped v74 SQL.
alter table public.suggestions drop constraint if exists suggestion_status_check;
alter table public.suggestions
  add constraint suggestion_status_check check (status in ('pending', 'approved', 'denied', 'rejected'));

drop policy if exists "profiles_select_all" on public.profiles;
drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles
for select
to anon, authenticated
using (true);

drop policy if exists "suggestions_select_approved_or_own_or_admin" on public.suggestions;
drop policy if exists "suggestions_select_public_or_own_or_admin" on public.suggestions;
create policy "suggestions_select_public_or_own_or_admin"
on public.suggestions
for select
to anon, authenticated
using (
  status = 'approved'
  or user_id = auth.uid()
  or public.is_blank_space_admin()
);

create table if not exists public.friends (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint friends_no_self check (requester_id <> receiver_id),
  constraint friends_status_check check (status in ('pending', 'accepted', 'declined'))
);

create unique index if not exists friends_one_connection_per_pair
on public.friends ((least(requester_id, receiver_id)), (greatest(requester_id, receiver_id)));

alter table public.friends enable row level security;

drop trigger if exists friends_set_updated_at on public.friends;
create trigger friends_set_updated_at
before update on public.friends
for each row
execute function public.set_updated_at();

drop policy if exists "friends_select_own" on public.friends;
drop policy if exists "friends_insert_own_pending" on public.friends;
drop policy if exists "friends_update_receiver_response" on public.friends;
drop policy if exists "friends_delete_own" on public.friends;

create policy "friends_select_own"
on public.friends
for select
to authenticated
using (requester_id = auth.uid() or receiver_id = auth.uid());

create policy "friends_insert_own_pending"
on public.friends
for insert
to authenticated
with check (requester_id = auth.uid() and status = 'pending');

create policy "friends_update_receiver_response"
on public.friends
for update
to authenticated
using (receiver_id = auth.uid() and status = 'pending')
with check (receiver_id = auth.uid() and status in ('accepted', 'declined'));

create policy "friends_delete_own"
on public.friends
for delete
to authenticated
using (requester_id = auth.uid() or receiver_id = auth.uid());

-- v75 profile fields.
alter table public.profiles
  add column if not exists avatar_url text,
  add column if not exists points integer not null default 0,
  add column if not exists username_last_changed_at timestamptz;

alter table public.profiles drop constraint if exists profiles_points_nonnegative;
alter table public.profiles add constraint profiles_points_nonnegative check (points >= 0);

-- v75 suggestion award field.
alter table public.suggestions
  add column if not exists points_awarded integer not null default 0;

alter table public.suggestions drop constraint if exists suggestions_points_awarded_nonnegative;
alter table public.suggestions add constraint suggestions_points_awarded_nonnegative check (points_awarded >= 0);

-- Protect points and username timing even though users can update their own profile.
create or replace function public.profiles_update_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.id is distinct from old.id then
    raise exception 'Profile ID cannot be changed.';
  end if;

  if new.created_at is distinct from old.created_at then
    raise exception 'Profile creation time cannot be changed.';
  end if;

  if not public.is_blank_space_admin() and new.points is distinct from old.points then
    raise exception 'Points can only be changed by an admin award.';
  end if;

  if new.username is distinct from old.username then
    if old.username_last_changed_at is not null and old.username_last_changed_at > now() - interval '7 days' then
      raise exception 'You can only change your username once every 7 days.';
    end if;
    new.username_last_changed_at := now();
  elsif new.username_last_changed_at is distinct from old.username_last_changed_at then
    raise exception 'Username timer cannot be changed directly.';
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_update_guard_trigger on public.profiles;
create trigger profiles_update_guard_trigger
before update on public.profiles
for each row
execute function public.profiles_update_guard();

-- Admin function: approve/deny/pending a suggestion and adjust points safely.
create or replace function public.admin_set_suggestion_status(
  suggestion_id_input bigint,
  new_status text,
  award_points integer default 0
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_suggestion public.suggestions%rowtype;
  previous_points integer;
  next_points integer;
begin
  if not public.is_blank_space_admin() then
    raise exception 'Admin only.';
  end if;

  if new_status not in ('pending', 'approved', 'denied', 'rejected') then
    raise exception 'Invalid suggestion status.';
  end if;

  award_points := greatest(0, least(coalesce(award_points, 0), 10000));

  select * into old_suggestion
  from public.suggestions
  where id = suggestion_id_input
  for update;

  if not found then
    raise exception 'Suggestion not found.';
  end if;

  previous_points := coalesce(old_suggestion.points_awarded, 0);
  next_points := case when new_status = 'approved' then award_points else 0 end;

  update public.profiles
  set points = greatest(0, points - previous_points + next_points)
  where id = old_suggestion.user_id;

  update public.suggestions
  set status = new_status,
      points_awarded = next_points
  where id = suggestion_id_input;
end;
$$;

grant execute on function public.admin_set_suggestion_status(bigint, text, integer) to authenticated;

-- Public avatar storage bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/png','image/jpeg','image/webp','image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "avatar_public_read" on storage.objects;
drop policy if exists "avatar_owner_upload" on storage.objects;
drop policy if exists "avatar_owner_update" on storage.objects;
drop policy if exists "avatar_owner_delete" on storage.objects;

create policy "avatar_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'avatars');

create policy "avatar_owner_upload"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatar_owner_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatar_owner_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- To make yourself admin after creating your account, replace USER_ID_HERE with your User ID:
-- insert into public.admin_users (user_id) values ('USER_ID_HERE') on conflict (user_id) do nothing;
