-- Blank Space v81 Supabase update
-- Safe update: adds achievements/equipped icons/game progress and fixes Delete Account.
-- This does NOT delete existing accounts, points, friends, suggestions, or messages.

alter table public.profiles
  add column if not exists equipped_icon text,
  add column if not exists equipped_achievement_id text,
  add column if not exists points integer not null default 0;

-- Game progress tracked by the website. This is reliable website-side progress,
-- not deep in-game score reading for compiled/iframe games.
create table if not exists public.game_stats (
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_title text not null,
  play_count integer not null default 0,
  play_seconds integer not null default 0,
  first_played_at timestamptz not null default now(),
  last_played_at timestamptz not null default now(),
  primary key (user_id, game_title),
  constraint game_stats_title_length check (char_length(game_title) between 1 and 120),
  constraint game_stats_nonnegative check (play_count >= 0 and play_seconds >= 0)
);

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id text not null,
  title text not null,
  description text not null,
  icon text not null,
  game_title text,
  reward_points integer not null default 0,
  earned_at timestamptz not null default now(),
  primary key (user_id, achievement_id),
  constraint achievement_id_length check (char_length(achievement_id) between 2 and 80),
  constraint achievement_title_length check (char_length(title) between 2 and 80),
  constraint achievement_description_length check (char_length(description) between 2 and 240),
  constraint achievement_icon_length check (char_length(icon) between 1 and 16),
  constraint achievement_reward_nonnegative check (reward_points >= 0 and reward_points <= 10000)
);

create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friends(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint friend_messages_body_length check (char_length(body) between 1 and 500)
);

create index if not exists friend_messages_friendship_created_idx
on public.friend_messages (friendship_id, created_at);

alter table public.game_stats enable row level security;
alter table public.user_achievements enable row level security;
alter table public.friend_messages enable row level security;

-- RLS policies for game stats
drop policy if exists "game_stats_select_own" on public.game_stats;
drop policy if exists "game_stats_insert_own" on public.game_stats;
drop policy if exists "game_stats_update_own" on public.game_stats;

create policy "game_stats_select_own"
on public.game_stats
for select
to authenticated
using (user_id = auth.uid() or public.is_blank_space_admin());

create policy "game_stats_insert_own"
on public.game_stats
for insert
to authenticated
with check (user_id = auth.uid());

create policy "game_stats_update_own"
on public.game_stats
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- RLS policies for achievements
drop policy if exists "user_achievements_select_own_or_admin" on public.user_achievements;
drop policy if exists "user_achievements_insert_own" on public.user_achievements;
drop policy if exists "user_achievements_update_own" on public.user_achievements;

create policy "user_achievements_select_own_or_admin"
on public.user_achievements
for select
to authenticated
using (user_id = auth.uid() or public.is_blank_space_admin());

create policy "user_achievements_insert_own"
on public.user_achievements
for insert
to authenticated
with check (user_id = auth.uid());

create policy "user_achievements_update_own"
on public.user_achievements
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- RLS policies for friend chat, safe to re-run.
drop policy if exists "friend_messages_select_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_insert_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_delete_sender_or_admin" on public.friend_messages;

create policy "friend_messages_select_own_friendship"
on public.friend_messages
for select
to authenticated
using (
  exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_insert_own_friendship"
on public.friend_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_delete_sender_or_admin"
on public.friend_messages
for delete
to authenticated
using (sender_id = auth.uid() or public.is_blank_space_admin());

-- Record reliable website-side progress for a game.
create or replace function public.record_game_progress(
  p_game_title text,
  p_open_event boolean default false,
  p_seconds integer default 0
)
returns table (
  game_title text,
  play_count integer,
  play_seconds integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  add_count integer := case when coalesce(p_open_event, false) then 1 else 0 end;
  add_seconds integer := greatest(0, coalesce(p_seconds, 0));
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  if p_game_title is null or char_length(trim(p_game_title)) < 1 then
    raise exception 'Game title is required.';
  end if;

  insert into public.game_stats (user_id, game_title, play_count, play_seconds)
  values (uid, trim(p_game_title), add_count, add_seconds)
  on conflict (user_id, game_title)
  do update set
    play_count = public.game_stats.play_count + excluded.play_count,
    play_seconds = public.game_stats.play_seconds + excluded.play_seconds,
    last_played_at = now();

  return query
  select gs.game_title, gs.play_count, gs.play_seconds
  from public.game_stats gs
  where gs.user_id = uid and gs.game_title = trim(p_game_title);
end;
$$;

grant execute on function public.record_game_progress(text, boolean, integer) to authenticated;

-- Award an achievement once. If it is new, also adds reward points.
create or replace function public.award_achievement(
  p_achievement_id text,
  p_title text,
  p_description text,
  p_icon text,
  p_game_title text default null,
  p_reward_points integer default 0
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  inserted_count integer := 0;
  safe_points integer := greatest(0, least(coalesce(p_reward_points, 0), 10000));
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  insert into public.user_achievements (user_id, achievement_id, title, description, icon, game_title, reward_points)
  values (uid, p_achievement_id, p_title, p_description, p_icon, p_game_title, safe_points)
  on conflict (user_id, achievement_id) do nothing;

  get diagnostics inserted_count = row_count;

  if inserted_count > 0 then
    update public.profiles
    set points = coalesce(points, 0) + safe_points,
        equipped_icon = coalesce(equipped_icon, p_icon),
        equipped_achievement_id = coalesce(equipped_achievement_id, p_achievement_id)
    where id = uid;
    return true;
  end if;

  return false;
end;
$$;

grant execute on function public.award_achievement(text, text, text, text, text, integer) to authenticated;

create or replace function public.equip_achievement_icon(p_achievement_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  chosen_icon text;
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  select ua.icon into chosen_icon
  from public.user_achievements ua
  where ua.user_id = uid
    and ua.achievement_id = p_achievement_id;

  if chosen_icon is null then
    raise exception 'You have not unlocked that icon yet.';
  end if;

  update public.profiles
  set equipped_icon = chosen_icon,
      equipped_achievement_id = p_achievement_id
  where id = uid;
end;
$$;

grant execute on function public.equip_achievement_icon(text) to authenticated;

-- Public leaderboard now includes equipped icon and still hides admins.
create or replace function public.get_public_leaderboard(max_rows integer default 100)
returns table (
  id uuid,
  username text,
  avatar_url text,
  points integer,
  equipped_icon text
)
language sql
security definer
set search_path = public
as $$
  select p.id, p.username, p.avatar_url, p.points, p.equipped_icon
  from public.profiles p
  where not exists (
    select 1
    from public.admin_users a
    where a.user_id = p.id
  )
  order by p.points desc, lower(p.username) asc
  limit greatest(1, least(coalesce(max_rows, 100), 100));
$$;

grant execute on function public.get_public_leaderboard(integer) to anon, authenticated;

-- Corrected account deletion helper: handles whichever optional tables/columns exist.
create or replace function public.delete_rows_for_account_if_column_exists_v2(
  p_table_name text,
  p_column_name text,
  p_account_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_regclass(format('public.%I', p_table_name)) is not null
     and exists (
       select 1
       from information_schema.columns c
       where c.table_schema = 'public'
         and c.table_name = p_table_name
         and c.column_name = p_column_name
     )
  then
    execute format('delete from public.%I where %I = $1', p_table_name, p_column_name)
    using p_account_id;
  end if;
end;
$$;

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Not signed in.';
  end if;

  perform public.delete_rows_for_account_if_column_exists_v2('admin_users', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('admin_users', 'id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestion_reports', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestion_reports', 'reporter_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'profile_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'author_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('points_log', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('user_points', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('game_stats', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('user_achievements', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_messages', 'sender_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'sender_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'receiver_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'requester_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'addressee_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'from_user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'to_user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'requester_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'receiver_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'friend_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'user1_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'user2_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('profiles', 'id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('profiles', 'user_id', current_user_id);

  delete from auth.users where id = current_user_id;
end;
$$;

grant execute on function public.delete_my_account() to authenticated;
grant execute on function public.delete_rows_for_account_if_column_exists_v2(text, text, uuid) to authenticated;

-- Enable realtime for chat when available.
do $$
begin
  alter publication supabase_realtime add table public.friend_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

select pg_notify('pgrst', 'reload schema');
