-- Blank Space v89 update
-- Paste this full file into Supabase SQL Editor, then click Run.
-- Adds group chats, rank controls, admin moderation helpers, and a no-reset achievement repair.
-- This does NOT reset anyone's account, points, friends, icons, trades, or messages.

-- ===============================
-- 1) Ranks and moderation columns
-- ===============================
alter table public.profiles add column if not exists rank text not null default 'member';
alter table public.profiles add column if not exists is_banned boolean not null default false;
alter table public.profiles add column if not exists ban_reason text;
alter table public.profiles add column if not exists chat_muted_until timestamptz;
update public.profiles set rank = 'member' where rank is null or lower(rank) not in ('admin','manager','tester','member');

create table if not exists public.admin_users (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_blank_space_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users a where a.user_id = auth.uid())
     or exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.rank,'member')) = 'admin');
$$;

grant execute on function public.is_blank_space_admin() to anon, authenticated;

create table if not exists public.admin_actions_log (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_username text,
  action text not null,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.admin_actions_log enable row level security;
drop policy if exists "admin_actions_admin_select" on public.admin_actions_log;
create policy "admin_actions_admin_select" on public.admin_actions_log for select to authenticated using (public.is_blank_space_admin());

grant select, insert on table public.admin_actions_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.log_admin_action(p_target_user_id uuid, p_target_username text, p_action text, p_reason text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.admin_actions_log(admin_id, target_user_id, target_username, action, reason)
  values (auth.uid(), p_target_user_id, p_target_username, p_action, nullif(trim(coalesce(p_reason,'')),''));
end;
$$;

grant execute on function public.log_admin_action(uuid, text, text, text) to authenticated;

-- ===================================
-- 2) Profile guard with safe rank edits
-- ===================================
create or replace function public.profiles_update_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.id is distinct from old.id then raise exception 'Profile ID cannot be changed.'; end if;
  if new.created_at is distinct from old.created_at then raise exception 'Profile creation time cannot be changed.'; end if;
  if coalesce(current_setting('blank_space.allow_points_update', true), '') <> '1' and new.points is distinct from old.points then
    raise exception 'Points can only be changed by an approved Blank Space server function.';
  end if;
  if coalesce(current_setting('blank_space.allow_rank_update', true), '') <> '1' and new.rank is distinct from old.rank then
    raise exception 'Rank can only be changed by an approved Blank Space admin function.';
  end if;
  if coalesce(current_setting('blank_space.allow_moderation_update', true), '') <> '1' and (new.is_banned is distinct from old.is_banned or new.ban_reason is distinct from old.ban_reason or new.chat_muted_until is distinct from old.chat_muted_until) then
    raise exception 'Moderation fields can only be changed by an approved Blank Space admin function.';
  end if;
  if new.username is distinct from old.username then
    if coalesce(current_setting('blank_space.allow_username_update', true), '') <> '1' then
      if old.username_last_changed_at is not null and old.username_last_changed_at > now() - interval '7 days' then
        raise exception 'You can only change your username once every 7 days.';
      end if;
    end if;
    new.username_last_changed_at := now();
  elsif new.username_last_changed_at is distinct from old.username_last_changed_at then
    raise exception 'Username timer cannot be changed directly.';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_update_guard_trigger on public.profiles;
create trigger profiles_update_guard_trigger before update on public.profiles for each row execute function public.profiles_update_guard();

-- ===============================
-- 3) Admin rank and moderation RPC
-- ===============================
create or replace function public.admin_set_rank_v89(p_username text, p_rank text, p_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin uuid := auth.uid();
  v_target public.profiles%rowtype;
  v_rank text := lower(trim(coalesce(p_rank,'member')));
begin
  if v_admin is null or not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
  if v_rank not in ('admin','manager','tester','member') then raise exception 'Invalid rank.'; end if;
  select * into v_target from public.profiles where lower(username)=lower(trim(coalesce(p_username,''))) limit 1;
  if v_target.id is null then raise exception 'User not found.'; end if;
  perform set_config('blank_space.allow_rank_update','1',true);
  update public.profiles set rank = v_rank where id = v_target.id;
  if v_rank = 'admin' then
    insert into public.admin_users(user_id) values (v_target.id) on conflict (user_id) do nothing;
  else
    delete from public.admin_users where user_id = v_target.id;
  end if;
  perform public.log_admin_action(v_target.id, v_target.username, 'set_rank:' || v_rank, p_reason);
  return jsonb_build_object('ok', true, 'username', v_target.username, 'rank', v_rank);
end;
$$;

grant execute on function public.admin_set_rank_v89(text, text, text) to authenticated;

create or replace function public.admin_moderate_user_v89(p_username text, p_action text, p_reason text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin uuid := auth.uid();
  v_target public.profiles%rowtype;
  v_action text := lower(trim(coalesce(p_action,'')));
begin
  if v_admin is null or not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
  select * into v_target from public.profiles where lower(username)=lower(trim(coalesce(p_username,''))) limit 1;
  if v_target.id is null then raise exception 'User not found.'; end if;
  perform set_config('blank_space.allow_moderation_update','1',true);
  if v_action = 'mute_chat' then
    update public.profiles set chat_muted_until = now() + interval '7 days' where id = v_target.id;
  elsif v_action = 'unmute_chat' then
    update public.profiles set chat_muted_until = null where id = v_target.id;
  elsif v_action = 'ban_chat' then
    update public.profiles set is_banned = true, ban_reason = nullif(trim(coalesce(p_reason,'')),'') where id = v_target.id;
  elsif v_action = 'unban_chat' then
    update public.profiles set is_banned = false, ban_reason = null where id = v_target.id;
  elsif v_action = 'reset_achievements_keep_points' then
    delete from public.user_achievements where user_id = v_target.id;
  elsif v_action = 'clear_messages' then
    if to_regclass('public.friend_messages') is not null then
      delete from public.friend_messages where sender_id = v_target.id;
    end if;
    if to_regclass('public.group_chat_messages') is not null then
      delete from public.group_chat_messages where sender_id = v_target.id;
    end if;
  else
    raise exception 'Unknown moderation action.';
  end if;
  perform public.log_admin_action(v_target.id, v_target.username, v_action, p_reason);
  return jsonb_build_object('ok', true, 'username', v_target.username, 'action', v_action);
end;
$$;

grant execute on function public.admin_moderate_user_v89(text, text, text) to authenticated;

create or replace function public.enforce_chat_moderation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_banned boolean;
  v_muted_until timestamptz;
begin
  select is_banned, chat_muted_until into v_is_banned, v_muted_until from public.profiles where id = new.sender_id;
  if coalesce(v_is_banned,false) then raise exception 'You are banned from chat.'; end if;
  if v_muted_until is not null and v_muted_until > now() then raise exception 'You are muted from chat until %.', v_muted_until; end if;
  return new;
end;
$$;

do $$ begin
  if to_regclass('public.friend_messages') is not null then
    execute 'drop trigger if exists friend_messages_moderation_trigger on public.friend_messages';
    execute 'create trigger friend_messages_moderation_trigger before insert on public.friend_messages for each row execute function public.enforce_chat_moderation()';
  end if;
end $$;

-- ===============================
-- 4) Group chats backend
-- ===============================
-- Blank Space group chats backend
-- Paste this entire file into Supabase SQL Editor, then click Run.
-- This creates Supabase tables + functions for group chats.
-- You will still need a GitHub website update to show the group chat UI on the site.

-- 1) Tables
create table if not exists public.group_chats (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint group_chats_name_length check (char_length(trim(name)) between 1 and 40)
);

create table if not exists public.group_chat_members (
  group_id bigint not null references public.group_chats(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member',
  invited_by uuid references public.profiles(id) on delete set null,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id),
  constraint group_chat_members_role_check check (role in ('owner', 'admin', 'member'))
);

create table if not exists public.group_chat_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.group_chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text,
  image_url text,
  created_at timestamptz not null default now(),
  constraint group_chat_messages_content_check check (
    (body is not null and char_length(trim(body)) between 1 and 1000)
    or
    (image_url is not null and char_length(trim(image_url)) between 1 and 2000)
  )
);

create index if not exists group_chats_owner_idx on public.group_chats(owner_id);
create index if not exists group_chat_members_user_idx on public.group_chat_members(user_id);
create index if not exists group_chat_messages_group_created_idx on public.group_chat_messages(group_id, created_at desc);
create index if not exists group_chat_messages_sender_idx on public.group_chat_messages(sender_id);

-- 2) Helper functions used by RLS. These avoid recursive policy errors.
create or replace function public.is_group_chat_member(p_group_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.group_chat_members m
    where m.group_id = p_group_id
      and m.user_id = p_user_id
  );
$$;

create or replace function public.can_manage_group_chat(p_group_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.group_chat_members m
    where m.group_id = p_group_id
      and m.user_id = p_user_id
      and m.role in ('owner', 'admin')
  );
$$;

create or replace function public.are_accepted_friends(p_user_a uuid, p_user_b uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select p_user_a = p_user_b or exists (
    select 1
    from public.friends f
    where f.status = 'accepted'
      and (
        (f.requester_id = p_user_a and f.receiver_id = p_user_b)
        or
        (f.requester_id = p_user_b and f.receiver_id = p_user_a)
      )
  );
$$;

-- 3) Auto-update timestamps and auto-add the creator as owner.
create or replace function public.touch_group_chat_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_group_chat_updated_at on public.group_chats;
create trigger trg_touch_group_chat_updated_at
before update on public.group_chats
for each row
execute function public.touch_group_chat_updated_at();

create or replace function public.add_group_chat_owner_member()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.group_chat_members(group_id, user_id, role, invited_by)
  values (new.id, new.owner_id, 'owner', new.owner_id)
  on conflict (group_id, user_id) do update set role = 'owner';
  return new;
end;
$$;

drop trigger if exists trg_add_group_chat_owner_member on public.group_chats;
create trigger trg_add_group_chat_owner_member
after insert on public.group_chats
for each row
execute function public.add_group_chat_owner_member();

-- 4) Row Level Security
alter table public.group_chats enable row level security;
alter table public.group_chat_members enable row level security;
alter table public.group_chat_messages enable row level security;

drop policy if exists "group_chats_select_member" on public.group_chats;
drop policy if exists "group_chats_insert_own" on public.group_chats;
drop policy if exists "group_chats_update_manager" on public.group_chats;
drop policy if exists "group_chats_delete_manager" on public.group_chats;

create policy "group_chats_select_member"
on public.group_chats
for select
to authenticated
using (public.is_group_chat_member(id, auth.uid()));

create policy "group_chats_insert_own"
on public.group_chats
for insert
to authenticated
with check (owner_id = auth.uid());

create policy "group_chats_update_manager"
on public.group_chats
for update
to authenticated
using (public.can_manage_group_chat(id, auth.uid()))
with check (public.can_manage_group_chat(id, auth.uid()));

create policy "group_chats_delete_manager"
on public.group_chats
for delete
to authenticated
using (public.can_manage_group_chat(id, auth.uid()));

drop policy if exists "group_chat_members_select_group_member" on public.group_chat_members;
drop policy if exists "group_chat_members_insert_manager" on public.group_chat_members;
drop policy if exists "group_chat_members_update_manager" on public.group_chat_members;
drop policy if exists "group_chat_members_delete_self_or_manager" on public.group_chat_members;

create policy "group_chat_members_select_group_member"
on public.group_chat_members
for select
to authenticated
using (public.is_group_chat_member(group_id, auth.uid()));

create policy "group_chat_members_insert_manager"
on public.group_chat_members
for insert
to authenticated
with check (public.can_manage_group_chat(group_id, auth.uid()));

create policy "group_chat_members_update_manager"
on public.group_chat_members
for update
to authenticated
using (public.can_manage_group_chat(group_id, auth.uid()))
with check (public.can_manage_group_chat(group_id, auth.uid()));

create policy "group_chat_members_delete_self_or_manager"
on public.group_chat_members
for delete
to authenticated
using (user_id = auth.uid() or public.can_manage_group_chat(group_id, auth.uid()));

drop policy if exists "group_chat_messages_select_member" on public.group_chat_messages;
drop policy if exists "group_chat_messages_insert_member" on public.group_chat_messages;
drop policy if exists "group_chat_messages_delete_sender_or_manager" on public.group_chat_messages;

create policy "group_chat_messages_select_member"
on public.group_chat_messages
for select
to authenticated
using (public.is_group_chat_member(group_id, auth.uid()));

create policy "group_chat_messages_insert_member"
on public.group_chat_messages
for insert
to authenticated
with check (sender_id = auth.uid() and public.is_group_chat_member(group_id, auth.uid()));

create policy "group_chat_messages_delete_sender_or_manager"
on public.group_chat_messages
for delete
to authenticated
using (sender_id = auth.uid() or public.can_manage_group_chat(group_id, auth.uid()));

-- 5) RPC functions for the website to call.
create or replace function public.create_group_chat(p_name text, p_member_ids uuid[] default '{}')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_name text := trim(coalesce(p_name, ''));
  v_group_id bigint;
  v_member uuid;
  v_added integer := 0;
begin
  if v_uid is null then
    raise exception 'Not signed in.';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'Group chat name must be 1 to 40 characters.';
  end if;

  insert into public.group_chats(name, owner_id)
  values (v_name, v_uid)
  returning id into v_group_id;

  insert into public.group_chat_members(group_id, user_id, role, invited_by)
  values (v_group_id, v_uid, 'owner', v_uid)
  on conflict (group_id, user_id) do update set role = 'owner';

  foreach v_member in array coalesce(p_member_ids, '{}'::uuid[]) loop
    if v_member is not null
       and v_member <> v_uid
       and public.are_accepted_friends(v_uid, v_member) then
      insert into public.group_chat_members(group_id, user_id, role, invited_by)
      values (v_group_id, v_member, 'member', v_uid)
      on conflict do nothing;
      v_added := v_added + 1;
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'group_id', v_group_id, 'added_members', v_added);
end;
$$;

create or replace function public.create_group_chat_by_usernames(p_name text, p_usernames text[] default '{}')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text;
  v_member uuid;
  v_ids uuid[] := '{}'::uuid[];
begin
  foreach v_username in array coalesce(p_usernames, '{}'::text[]) loop
    select id into v_member
    from public.profiles
    where lower(username) = lower(trim(v_username))
    limit 1;

    if v_member is not null then
      v_ids := array_append(v_ids, v_member);
    end if;
  end loop;

  return public.create_group_chat(p_name, v_ids);
end;
$$;

create or replace function public.add_group_chat_members(p_group_id bigint, p_member_ids uuid[] default '{}')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_member uuid;
  v_added integer := 0;
begin
  if v_uid is null then
    raise exception 'Not signed in.';
  end if;

  if not public.can_manage_group_chat(p_group_id, v_uid) then
    raise exception 'Only a group owner or group admin can add members.';
  end if;

  foreach v_member in array coalesce(p_member_ids, '{}'::uuid[]) loop
    if v_member is not null
       and v_member <> v_uid
       and public.are_accepted_friends(v_uid, v_member) then
      insert into public.group_chat_members(group_id, user_id, role, invited_by)
      values (p_group_id, v_member, 'member', v_uid)
      on conflict do nothing;
      v_added := v_added + 1;
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'group_id', p_group_id, 'added_members', v_added);
end;
$$;

create or replace function public.add_group_chat_members_by_usernames(p_group_id bigint, p_usernames text[] default '{}')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text;
  v_member uuid;
  v_ids uuid[] := '{}'::uuid[];
begin
  foreach v_username in array coalesce(p_usernames, '{}'::text[]) loop
    select id into v_member
    from public.profiles
    where lower(username) = lower(trim(v_username))
    limit 1;

    if v_member is not null then
      v_ids := array_append(v_ids, v_member);
    end if;
  end loop;

  return public.add_group_chat_members(p_group_id, v_ids);
end;
$$;

create or replace function public.send_group_chat_message(
  p_group_id bigint,
  p_body text default null,
  p_image_url text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_body text := nullif(trim(coalesce(p_body, '')), '');
  v_image_url text := nullif(trim(coalesce(p_image_url, '')), '');
  v_message_id bigint;
  v_created_at timestamptz;
begin
  if v_uid is null then
    raise exception 'Not signed in.';
  end if;

  if not public.is_group_chat_member(p_group_id, v_uid) then
    raise exception 'You are not a member of this group chat.';
  end if;

  if v_body is null and v_image_url is null then
    raise exception 'Message cannot be empty.';
  end if;

  if v_body is not null and char_length(v_body) > 1000 then
    raise exception 'Message is too long.';
  end if;

  insert into public.group_chat_messages(group_id, sender_id, body, image_url)
  values (p_group_id, v_uid, v_body, v_image_url)
  returning id, created_at into v_message_id, v_created_at;

  update public.group_chats
  set updated_at = now()
  where id = p_group_id;

  return jsonb_build_object('ok', true, 'message_id', v_message_id, 'created_at', v_created_at);
end;
$$;

create or replace function public.rename_group_chat(p_group_id bigint, p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_name text := trim(coalesce(p_name, ''));
begin
  if v_uid is null then
    raise exception 'Not signed in.';
  end if;

  if not public.can_manage_group_chat(p_group_id, v_uid) then
    raise exception 'Only a group owner or group admin can rename this group.';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'Group chat name must be 1 to 40 characters.';
  end if;

  update public.group_chats
  set name = v_name, updated_at = now()
  where id = p_group_id;

  return jsonb_build_object('ok', true, 'group_id', p_group_id, 'name', v_name);
end;
$$;

create or replace function public.leave_group_chat(p_group_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_my_role text;
  v_new_owner uuid;
begin
  if v_uid is null then
    raise exception 'Not signed in.';
  end if;

  select role into v_my_role
  from public.group_chat_members
  where group_id = p_group_id and user_id = v_uid;

  if v_my_role is null then
    raise exception 'You are not in this group chat.';
  end if;

  if v_my_role = 'owner' then
    select user_id into v_new_owner
    from public.group_chat_members
    where group_id = p_group_id and user_id <> v_uid
    order by joined_at asc
    limit 1;

    if v_new_owner is null then
      delete from public.group_chats where id = p_group_id;
      return jsonb_build_object('ok', true, 'deleted_group', true);
    end if;

    update public.group_chat_members
    set role = 'owner'
    where group_id = p_group_id and user_id = v_new_owner;

    update public.group_chats
    set owner_id = v_new_owner, updated_at = now()
    where id = p_group_id;
  end if;

  delete from public.group_chat_members
  where group_id = p_group_id and user_id = v_uid;

  return jsonb_build_object('ok', true, 'left_group', true, 'new_owner', v_new_owner);
end;
$$;

create or replace function public.delete_group_chat(p_group_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Not signed in.';
  end if;

  if not public.can_manage_group_chat(p_group_id, v_uid) then
    raise exception 'Only a group owner or group admin can delete this group.';
  end if;

  delete from public.group_chats where id = p_group_id;
  return jsonb_build_object('ok', true, 'deleted_group', true);
end;
$$;

-- 6) Read helpers for the website.
create or replace function public.get_my_group_chats()
returns table (
  id bigint,
  name text,
  owner_id uuid,
  my_role text,
  member_count bigint,
  last_message_body text,
  last_message_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;

  return query
  select
    g.id,
    g.name,
    g.owner_id,
    m.role as my_role,
    (select count(*) from public.group_chat_members cm where cm.group_id = g.id) as member_count,
    (select gm.body from public.group_chat_messages gm where gm.group_id = g.id order by gm.created_at desc limit 1) as last_message_body,
    (select gm.created_at from public.group_chat_messages gm where gm.group_id = g.id order by gm.created_at desc limit 1) as last_message_at,
    g.updated_at
  from public.group_chats g
  join public.group_chat_members m on m.group_id = g.id and m.user_id = auth.uid()
  order by coalesce(
    (select max(gm2.created_at) from public.group_chat_messages gm2 where gm2.group_id = g.id),
    g.updated_at
  ) desc;
end;
$$;

create or replace function public.get_group_chat_members(p_group_id bigint)
returns table (
  user_id uuid,
  username text,
  avatar_url text,
  role text,
  joined_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;

  if not public.is_group_chat_member(p_group_id, auth.uid()) then
    raise exception 'You are not a member of this group chat.';
  end if;

  return query
  select
    m.user_id,
    p.username,
    p.avatar_url,
    m.role,
    m.joined_at
  from public.group_chat_members m
  join public.profiles p on p.id = m.user_id
  where m.group_id = p_group_id
  order by
    case m.role when 'owner' then 1 when 'admin' then 2 else 3 end,
    lower(p.username) asc;
end;
$$;

drop function if exists public.get_group_chat_messages(bigint, integer);
create function public.get_group_chat_messages(p_group_id bigint, p_limit integer default 50)
returns table (
  id bigint,
  group_id bigint,
  sender_id uuid,
  sender_username text,
  sender_avatar_url text,
  sender_rank text,
  body text,
  image_url text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;

  if not public.is_group_chat_member(p_group_id, auth.uid()) then
    raise exception 'You are not a member of this group chat.';
  end if;

  return query
  select
    gm.id,
    gm.group_id,
    gm.sender_id,
    p.username as sender_username,
    p.avatar_url as sender_avatar_url,
    coalesce(p.rank, 'member') as sender_rank,
    gm.body,
    gm.image_url,
    gm.created_at
  from public.group_chat_messages gm
  join public.profiles p on p.id = gm.sender_id
  where gm.group_id = p_group_id
  order by gm.created_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 100));
end;
$$;

-- 7) Permissions
revoke all on table public.group_chats from anon;
revoke all on table public.group_chat_members from anon;
revoke all on table public.group_chat_messages from anon;

grant select, insert, update, delete on table public.group_chats to authenticated;
grant select, insert, update, delete on table public.group_chat_members to authenticated;
grant select, insert, delete on table public.group_chat_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.is_group_chat_member(bigint, uuid) to authenticated;
grant execute on function public.can_manage_group_chat(bigint, uuid) to authenticated;
grant execute on function public.are_accepted_friends(uuid, uuid) to authenticated;
grant execute on function public.create_group_chat(text, uuid[]) to authenticated;
grant execute on function public.create_group_chat_by_usernames(text, text[]) to authenticated;
grant execute on function public.add_group_chat_members(bigint, uuid[]) to authenticated;
grant execute on function public.add_group_chat_members_by_usernames(bigint, text[]) to authenticated;
grant execute on function public.send_group_chat_message(bigint, text, text) to authenticated;
grant execute on function public.rename_group_chat(bigint, text) to authenticated;
grant execute on function public.leave_group_chat(bigint) to authenticated;
grant execute on function public.delete_group_chat(bigint) to authenticated;
grant execute on function public.get_my_group_chats() to authenticated;
grant execute on function public.get_group_chat_members(bigint) to authenticated;
grant execute on function public.get_group_chat_messages(bigint, integer) to authenticated;

-- 8) Enable realtime for group chats when available.
do $$
begin
  alter publication supabase_realtime add table public.group_chats;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.group_chat_members;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.group_chat_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;




do $$ begin
  if to_regclass('public.group_chat_messages') is not null then
    execute 'drop trigger if exists group_chat_messages_moderation_trigger on public.group_chat_messages';
    execute 'create trigger group_chat_messages_moderation_trigger before insert on public.group_chat_messages for each row execute function public.enforce_chat_moderation()';
  end if;
end $$;

-- ========================================
-- 5) Achievement catalog and no-reset repair
-- ========================================
create table if not exists public.game_stats (
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_title text not null,
  play_count integer not null default 0,
  play_seconds integer not null default 0,
  first_played_at timestamptz not null default now(),
  last_played_at timestamptz not null default now(),
  primary key (user_id, game_title)
);

alter table public.game_stats
  add column if not exists best_score integer not null default 0,
  add column if not exists goals integer not null default 0,
  add column if not exists wins integer not null default 0,
  add column if not exists fish_caught integer not null default 0,
  add column if not exists money_earned integer not null default 0,
  add column if not exists checks integer not null default 0,
  add column if not exists checkmates integer not null default 0,
  add column if not exists merges integer not null default 0,
  add column if not exists best_level integer not null default 0,
  add column if not exists hits integer not null default 0;

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id text not null,
  title text not null,
  description text not null,
  icon text not null,
  game_title text,
  reward_points integer not null default 0,
  earned_at timestamptz not null default now(),
  primary key (user_id, achievement_id)
);

create table if not exists public.achievement_catalog (
  achievement_id text primary key,
  title text not null,
  description text not null,
  icon text not null,
  game_title text,
  stat text not null,
  target integer not null,
  reward_points integer not null default 0,
  difficulty text default 'medium'
);

insert into public.achievement_catalog(achievement_id,title,description,icon,game_title,stat,target,reward_points,difficulty)
values
  ('google_snake_best_score_10_0','10 points','Get 10 points in Google Snake','🐍','Google Snake','best_score',10,2,'not_so_hard'),
  ('google_snake_best_score_20_1','20 points','Get 20 points in Google Snake','🐍','Google Snake','best_score',20,5,'medium'),
  ('google_snake_best_score_30_2','30 points','Get 30 points in Google Snake','🐍','Google Snake','best_score',30,5,'medium'),
  ('google_snake_best_score_40_3','40 points','Get 40 points in Google Snake','🐍','Google Snake','best_score',40,5,'medium'),
  ('google_snake_best_score_50_4','50 points','Get 50 points in Google Snake','🐍','Google Snake','best_score',50,5,'medium'),
  ('google_snake_best_score_60_5','60 points','Get 60 points in Google Snake','🐍','Google Snake','best_score',60,10,'hard'),
  ('google_snake_best_score_75_6','75 points','Get 75 points in Google Snake','🐍','Google Snake','best_score',75,10,'hard'),
  ('google_snake_best_score_90_7','90 points','Get 90 points in Google Snake','🐍','Google Snake','best_score',90,10,'hard'),
  ('google_snake_best_score_100_8','100 points','Get 100 points in Google Snake','🐍','Google Snake','best_score',100,10,'hard'),
  ('google_snake_best_score_125_9','125 points','Get 125 points in Google Snake','🐍','Google Snake','best_score',125,10,'hard'),
  ('google_snake_best_score_150_10','150 points','Get 150 points in Google Snake','🐍','Google Snake','best_score',150,10,'hard'),
  ('google_snake_best_score_175_11','175 points','Get 175 points in Google Snake','🐍','Google Snake','best_score',175,20,'crazy'),
  ('google_snake_best_score_200_12','200 points','Get 200 points in Google Snake','🐍','Google Snake','best_score',200,20,'crazy'),
  ('google_snake_best_score_250_13','250 points','Get 250 points in Google Snake','🐍','Google Snake','best_score',250,20,'crazy'),
  ('google_snake_best_score_300_14','300 points','Get 300 points in Google Snake','🐍','Google Snake','best_score',300,20,'crazy'),
  ('google_snake_best_score_350_15','350 points','Get 350 points in Google Snake','🐍','Google Snake','best_score',350,20,'crazy'),
  ('google_snake_best_score_400_16','400 points','Get 400 points in Google Snake','🐍','Google Snake','best_score',400,20,'crazy'),
  ('google_snake_best_score_500_17','500 points','Get 500 points in Google Snake','🐍','Google Snake','best_score',500,20,'crazy'),
  ('slope_best_score_25_18','Get 10 points in Slope','Get 10 points in one Slope round','🟢','Slope','best_score',10,2,'not_so_hard'),
  ('slope_best_score_50_19','Get 20 points in Slope','Get 20 points in one Slope round','🟢','Slope','best_score',20,2,'not_so_hard'),
  ('slope_best_score_75_20','Get 30 points in Slope','Get 30 points in one Slope round','🟢','Slope','best_score',30,2,'not_so_hard'),
  ('slope_best_score_100_21','Get 40 points in Slope','Get 40 points in one Slope round','🟢','Slope','best_score',40,2,'not_so_hard'),
  ('slope_best_score_125_22','Get 50 points in Slope','Get 50 points in one Slope round','🟢','Slope','best_score',50,2,'not_so_hard'),
  ('slope_best_score_150_23','Get 60 points in Slope','Get 60 points in one Slope round','🟢','Slope','best_score',60,2,'not_so_hard'),
  ('slope_best_score_200_24','Get 75 points in Slope','Get 75 points in one Slope round','🟢','Slope','best_score',75,5,'medium'),
  ('slope_best_score_250_25','Get 90 points in Slope','Get 90 points in one Slope round','🟢','Slope','best_score',90,5,'medium'),
  ('slope_best_score_300_26','Get 110 points in Slope','Get 110 points in one Slope round','🟢','Slope','best_score',110,5,'medium'),
  ('slope_best_score_400_27','Get 130 points in Slope','Get 130 points in one Slope round','🟢','Slope','best_score',130,5,'medium'),
  ('slope_best_score_500_28','Get 150 points in Slope','Get 150 points in one Slope round','🟢','Slope','best_score',150,5,'medium'),
  ('slope_best_score_650_29','Get 175 points in Slope','Get 175 points in one Slope round','🟢','Slope','best_score',175,10,'hard'),
  ('slope_best_score_800_30','Get 200 points in Slope','Get 200 points in one Slope round','🟢','Slope','best_score',200,10,'hard'),
  ('slope_best_score_1000_31','Get 250 points in Slope','Get 250 points in one Slope round','🟢','Slope','best_score',250,10,'hard'),
  ('slope_best_score_1250_32','Get 300 points in Slope','Get 300 points in one Slope round','🟢','Slope','best_score',300,10,'hard'),
  ('a_small_world_cup_goals_5_33','5 total goals','Score 5 total goals in A Small World Cup','⚽','A Small World Cup','goals',5,2,'not_so_hard'),
  ('a_small_world_cup_goals_10_34','10 total goals','Score 10 total goals in A Small World Cup','⚽','A Small World Cup','goals',10,2,'not_so_hard'),
  ('a_small_world_cup_goals_15_35','15 total goals','Score 15 total goals in A Small World Cup','⚽','A Small World Cup','goals',15,5,'medium'),
  ('a_small_world_cup_goals_20_36','20 total goals','Score 20 total goals in A Small World Cup','⚽','A Small World Cup','goals',20,5,'medium'),
  ('a_small_world_cup_goals_30_37','30 total goals','Score 30 total goals in A Small World Cup','⚽','A Small World Cup','goals',30,5,'medium'),
  ('a_small_world_cup_goals_40_38','40 total goals','Score 40 total goals in A Small World Cup','⚽','A Small World Cup','goals',40,5,'medium'),
  ('a_small_world_cup_goals_50_39','50 total goals','Score 50 total goals in A Small World Cup','⚽','A Small World Cup','goals',50,5,'medium'),
  ('a_small_world_cup_goals_75_40','75 total goals','Score 75 total goals in A Small World Cup','⚽','A Small World Cup','goals',75,10,'hard'),
  ('a_small_world_cup_goals_100_41','100 total goals','Score 100 total goals in A Small World Cup','⚽','A Small World Cup','goals',100,10,'hard'),
  ('a_small_world_cup_goals_150_42','150 total goals','Score 150 total goals in A Small World Cup','⚽','A Small World Cup','goals',150,10,'hard'),
  ('a_small_world_cup_goals_200_43','200 total goals','Score 200 total goals in A Small World Cup','⚽','A Small World Cup','goals',200,20,'crazy'),
  ('a_small_world_cup_goals_300_44','300 total goals','Score 300 total goals in A Small World Cup','⚽','A Small World Cup','goals',300,20,'crazy'),
  ('a_small_world_cup_wins_1_45','Win the World Cup 1 time(s)','Win the World Cup 1 time(s)','🏆','A Small World Cup','wins',1,2,'not_so_hard'),
  ('a_small_world_cup_wins_2_46','Win the World Cup 2 time(s)','Win the World Cup 2 time(s)','🏆','A Small World Cup','wins',2,5,'medium'),
  ('a_small_world_cup_wins_3_47','Win the World Cup 3 time(s)','Win the World Cup 3 time(s)','🏆','A Small World Cup','wins',3,5,'medium'),
  ('a_small_world_cup_wins_5_48','Win the World Cup 5 time(s)','Win the World Cup 5 time(s)','🏆','A Small World Cup','wins',5,5,'medium'),
  ('a_small_world_cup_wins_8_49','Win the World Cup 8 time(s)','Win the World Cup 8 time(s)','🏆','A Small World Cup','wins',8,10,'hard'),
  ('a_small_world_cup_wins_10_50','Win the World Cup 10 time(s)','Win the World Cup 10 time(s)','🏆','A Small World Cup','wins',10,10,'hard'),
  ('a_small_world_cup_wins_15_51','Win the World Cup 15 time(s)','Win the World Cup 15 time(s)','🏆','A Small World Cup','wins',15,10,'hard'),
  ('a_small_world_cup_wins_20_52','Win the World Cup 20 time(s)','Win the World Cup 20 time(s)','🏆','A Small World Cup','wins',20,20,'crazy'),
  ('a_small_world_cup_wins_30_53','Win the World Cup 30 time(s)','Win the World Cup 30 time(s)','🏆','A Small World Cup','wins',30,20,'crazy'),
  ('a_small_world_cup_wins_50_54','Win the World Cup 50 time(s)','Win the World Cup 50 time(s)','🏆','A Small World Cup','wins',50,20,'crazy'),
  ('basket_random_best_score_5_55','5 points','Score 5 points in Basket Random','🏀','Basket Random','best_score',5,2,'not_so_hard'),
  ('basket_random_best_score_10_56','10 points','Score 10 points in Basket Random','🏀','Basket Random','best_score',10,2,'not_so_hard'),
  ('basket_random_best_score_15_57','15 points','Score 15 points in Basket Random','🏀','Basket Random','best_score',15,5,'medium'),
  ('basket_random_best_score_20_58','20 points','Score 20 points in Basket Random','🏀','Basket Random','best_score',20,5,'medium'),
  ('basket_random_best_score_30_59','30 points','Score 30 points in Basket Random','🏀','Basket Random','best_score',30,5,'medium'),
  ('basket_random_best_score_40_60','40 points','Score 40 points in Basket Random','🏀','Basket Random','best_score',40,5,'medium'),
  ('basket_random_best_score_50_61','50 points','Score 50 points in Basket Random','🏀','Basket Random','best_score',50,5,'medium'),
  ('basket_random_best_score_75_62','75 points','Score 75 points in Basket Random','🏀','Basket Random','best_score',75,10,'hard'),
  ('basket_random_best_score_100_63','100 points','Score 100 points in Basket Random','🏀','Basket Random','best_score',100,10,'hard'),
  ('basket_random_best_score_150_64','150 points','Score 150 points in Basket Random','🏀','Basket Random','best_score',150,10,'hard'),
  ('basket_random_wins_1_65','Win 1 Basket Random match(es)','Win 1 Basket Random match(es)','🥇','Basket Random','wins',1,2,'not_so_hard'),
  ('basket_random_wins_3_66','Win 3 Basket Random match(es)','Win 3 Basket Random match(es)','🥇','Basket Random','wins',3,5,'medium'),
  ('basket_random_wins_5_67','Win 5 Basket Random match(es)','Win 5 Basket Random match(es)','🥇','Basket Random','wins',5,5,'medium'),
  ('basket_random_wins_10_68','Win 10 Basket Random match(es)','Win 10 Basket Random match(es)','🥇','Basket Random','wins',10,10,'hard'),
  ('basket_random_wins_15_69','Win 15 Basket Random match(es)','Win 15 Basket Random match(es)','🥇','Basket Random','wins',15,10,'hard'),
  ('basket_random_wins_25_70','Win 25 Basket Random match(es)','Win 25 Basket Random match(es)','🥇','Basket Random','wins',25,20,'crazy'),
  ('basket_random_wins_40_71','Win 40 Basket Random match(es)','Win 40 Basket Random match(es)','🥇','Basket Random','wins',40,20,'crazy'),
  ('basket_random_wins_60_72','Win 60 Basket Random match(es)','Win 60 Basket Random match(es)','🥇','Basket Random','wins',60,20,'crazy'),
  ('tiny_fishing_fish_caught_10_73','Catch 10 fish','Catch 10 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',10,2,'not_so_hard'),
  ('tiny_fishing_fish_caught_25_74','Catch 25 fish','Catch 25 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',25,5,'medium'),
  ('tiny_fishing_fish_caught_50_75','Catch 50 fish','Catch 50 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',50,5,'medium'),
  ('tiny_fishing_fish_caught_75_76','Catch 75 fish','Catch 75 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',75,10,'hard'),
  ('tiny_fishing_fish_caught_100_77','Catch 100 fish','Catch 100 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',100,10,'hard'),
  ('tiny_fishing_fish_caught_150_78','Catch 150 fish','Catch 150 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',150,10,'hard'),
  ('tiny_fishing_fish_caught_200_79','Catch 200 fish','Catch 200 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',200,20,'crazy'),
  ('tiny_fishing_fish_caught_300_80','Catch 300 fish','Catch 300 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',300,20,'crazy'),
  ('tiny_fishing_fish_caught_500_81','Catch 500 fish','Catch 500 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',500,20,'crazy'),
  ('tiny_fishing_fish_caught_750_82','Catch 750 fish','Catch 750 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',750,20,'crazy'),
  ('tiny_fishing_fish_caught_1000_83','Catch 1000 fish','Catch 1000 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',1000,20,'crazy'),
  ('tiny_fishing_money_earned_100_84','Earn $100','Earn $100 in Tiny Fishing','💰','Tiny Fishing','money_earned',100,10,'hard'),
  ('tiny_fishing_money_earned_250_85','Earn $250','Earn $250 in Tiny Fishing','💰','Tiny Fishing','money_earned',250,20,'crazy'),
  ('tiny_fishing_money_earned_500_86','Earn $500','Earn $500 in Tiny Fishing','💰','Tiny Fishing','money_earned',500,20,'crazy'),
  ('tiny_fishing_money_earned_1000_87','Earn $1000','Earn $1000 in Tiny Fishing','💰','Tiny Fishing','money_earned',1000,20,'crazy'),
  ('tiny_fishing_money_earned_2500_88','Earn $2500','Earn $2500 in Tiny Fishing','💰','Tiny Fishing','money_earned',2500,20,'crazy'),
  ('tiny_fishing_money_earned_5000_89','Earn $5000','Earn $5000 in Tiny Fishing','💰','Tiny Fishing','money_earned',5000,20,'crazy'),
  ('tiny_fishing_money_earned_10000_90','Earn $10000','Earn $10000 in Tiny Fishing','💰','Tiny Fishing','money_earned',10000,20,'crazy'),
  ('tiny_fishing_money_earned_25000_91','Earn $25000','Earn $25000 in Tiny Fishing','💰','Tiny Fishing','money_earned',25000,20,'crazy'),
  ('tiny_fishing_money_earned_50000_92','Earn $50000','Earn $50000 in Tiny Fishing','💰','Tiny Fishing','money_earned',50000,20,'crazy'),
  ('chess_ai_checks_1_93','Put the bot','Put the bot in check 1 time(s)','♟️','Chess-AI','checks',1,2,'not_so_hard'),
  ('chess_ai_checks_3_94','Put the bot','Put the bot in check 3 time(s)','♟️','Chess-AI','checks',3,2,'not_so_hard'),
  ('chess_ai_checks_5_95','Put the bot','Put the bot in check 5 time(s)','♟️','Chess-AI','checks',5,2,'not_so_hard'),
  ('chess_ai_checks_10_96','Put the bot','Put the bot in check 10 time(s)','♟️','Chess-AI','checks',10,2,'not_so_hard'),
  ('chess_ai_checks_15_97','Put the bot','Put the bot in check 15 time(s)','♟️','Chess-AI','checks',15,5,'medium'),
  ('chess_ai_checks_25_98','Put the bot','Put the bot in check 25 time(s)','♟️','Chess-AI','checks',25,5,'medium'),
  ('chess_ai_checks_40_99','Put the bot','Put the bot in check 40 time(s)','♟️','Chess-AI','checks',40,5,'medium'),
  ('chess_ai_checks_60_100','Put the bot','Put the bot in check 60 time(s)','♟️','Chess-AI','checks',60,10,'hard'),
  ('chess_ai_checks_100_101','Put the bot','Put the bot in check 100 time(s)','♟️','Chess-AI','checks',100,10,'hard'),
  ('chess_ai_checkmates_1_102','Checkmate the bot 1 time(s)','Checkmate the bot 1 time(s)','♚','Chess-AI','checkmates',1,2,'not_so_hard'),
  ('chess_ai_checkmates_2_103','Checkmate the bot 2 time(s)','Checkmate the bot 2 time(s)','♚','Chess-AI','checkmates',2,5,'medium'),
  ('chess_ai_checkmates_3_104','Checkmate the bot 3 time(s)','Checkmate the bot 3 time(s)','♚','Chess-AI','checkmates',3,5,'medium'),
  ('chess_ai_checkmates_5_105','Checkmate the bot 5 time(s)','Checkmate the bot 5 time(s)','♚','Chess-AI','checkmates',5,5,'medium'),
  ('chess_ai_checkmates_10_106','Checkmate the bot 10 time(s)','Checkmate the bot 10 time(s)','♚','Chess-AI','checkmates',10,10,'hard'),
  ('chess_ai_checkmates_15_107','Checkmate the bot 15 time(s)','Checkmate the bot 15 time(s)','♚','Chess-AI','checkmates',15,10,'hard'),
  ('chess_ai_checkmates_25_108','Checkmate the bot 25 time(s)','Checkmate the bot 25 time(s)','♚','Chess-AI','checkmates',25,20,'crazy'),
  ('chess_ai_checkmates_50_109','Checkmate the bot 50 time(s)','Checkmate the bot 50 time(s)','♚','Chess-AI','checkmates',50,20,'crazy'),
  ('chess_ai_wins_1_110','Beat the chess bot 1 time(s)','Beat the chess bot 1 time(s)','♛','Chess-AI','wins',1,2,'not_so_hard'),
  ('chess_ai_wins_2_111','Beat the chess bot 2 time(s)','Beat the chess bot 2 time(s)','♛','Chess-AI','wins',2,5,'medium'),
  ('chess_ai_wins_3_112','Beat the chess bot 3 time(s)','Beat the chess bot 3 time(s)','♛','Chess-AI','wins',3,5,'medium'),
  ('chess_ai_wins_5_113','Beat the chess bot 5 time(s)','Beat the chess bot 5 time(s)','♛','Chess-AI','wins',5,5,'medium'),
  ('chess_ai_wins_10_114','Beat the chess bot 10 time(s)','Beat the chess bot 10 time(s)','♛','Chess-AI','wins',10,10,'hard'),
  ('chess_ai_wins_15_115','Beat the chess bot 15 time(s)','Beat the chess bot 15 time(s)','♛','Chess-AI','wins',15,10,'hard'),
  ('chess_ai_wins_25_116','Beat the chess bot 25 time(s)','Beat the chess bot 25 time(s)','♛','Chess-AI','wins',25,20,'crazy'),
  ('chess_ai_wins_50_117','Beat the chess bot 50 time(s)','Beat the chess bot 50 time(s)','♛','Chess-AI','wins',50,20,'crazy'),
  ('stick_merge_merges_5_118','Merge weapons 5 time(s)','Merge weapons 5 time(s) in Stick Merge','🔫','Stick Merge','merges',5,2,'not_so_hard'),
  ('stick_merge_merges_10_119','Merge weapons 10 time(s)','Merge weapons 10 time(s) in Stick Merge','🔫','Stick Merge','merges',10,2,'not_so_hard'),
  ('stick_merge_merges_20_120','Merge weapons 20 time(s)','Merge weapons 20 time(s) in Stick Merge','🔫','Stick Merge','merges',20,5,'medium'),
  ('stick_merge_merges_35_121','Merge weapons 35 time(s)','Merge weapons 35 time(s) in Stick Merge','🔫','Stick Merge','merges',35,5,'medium'),
  ('stick_merge_merges_50_122','Merge weapons 50 time(s)','Merge weapons 50 time(s) in Stick Merge','🔫','Stick Merge','merges',50,5,'medium'),
  ('stick_merge_merges_75_123','Merge weapons 75 time(s)','Merge weapons 75 time(s) in Stick Merge','🔫','Stick Merge','merges',75,10,'hard'),
  ('stick_merge_merges_100_124','Merge weapons 100 time(s)','Merge weapons 100 time(s) in Stick Merge','🔫','Stick Merge','merges',100,10,'hard'),
  ('stick_merge_merges_150_125','Merge weapons 150 time(s)','Merge weapons 150 time(s) in Stick Merge','🔫','Stick Merge','merges',150,10,'hard'),
  ('stick_merge_merges_250_126','Merge weapons 250 time(s)','Merge weapons 250 time(s) in Stick Merge','🔫','Stick Merge','merges',250,20,'crazy'),
  ('stick_merge_merges_400_127','Merge weapons 400 time(s)','Merge weapons 400 time(s) in Stick Merge','🔫','Stick Merge','merges',400,20,'crazy'),
  ('stick_merge_merges_600_128','Merge weapons 600 time(s)','Merge weapons 600 time(s) in Stick Merge','🔫','Stick Merge','merges',600,20,'crazy'),
  ('stick_merge_best_level_2_129','Reach weapon level 2','Reach weapon level 2 in Stick Merge','🧪','Stick Merge','best_level',2,2,'not_so_hard'),
  ('stick_merge_best_level_3_130','Reach weapon level 3','Reach weapon level 3 in Stick Merge','🧪','Stick Merge','best_level',3,2,'not_so_hard'),
  ('stick_merge_best_level_4_131','Reach weapon level 4','Reach weapon level 4 in Stick Merge','🧪','Stick Merge','best_level',4,2,'not_so_hard'),
  ('stick_merge_best_level_5_132','Reach weapon level 5','Reach weapon level 5 in Stick Merge','🧪','Stick Merge','best_level',5,2,'not_so_hard'),
  ('stick_merge_best_level_6_133','Reach weapon level 6','Reach weapon level 6 in Stick Merge','🧪','Stick Merge','best_level',6,2,'not_so_hard'),
  ('stick_merge_best_level_7_134','Reach weapon level 7','Reach weapon level 7 in Stick Merge','🧪','Stick Merge','best_level',7,2,'not_so_hard'),
  ('stick_merge_best_level_8_135','Reach weapon level 8','Reach weapon level 8 in Stick Merge','🧪','Stick Merge','best_level',8,2,'not_so_hard'),
  ('stick_merge_best_level_10_136','Reach weapon level 10','Reach weapon level 10 in Stick Merge','🧪','Stick Merge','best_level',10,2,'not_so_hard'),
  ('stick_merge_best_level_12_137','Reach weapon level 12','Reach weapon level 12 in Stick Merge','🧪','Stick Merge','best_level',12,5,'medium'),
  ('stick_merge_best_level_15_138','Reach weapon level 15','Reach weapon level 15 in Stick Merge','🧪','Stick Merge','best_level',15,5,'medium'),
  ('stick_merge_best_level_20_139','Reach weapon level 20','Reach weapon level 20 in Stick Merge','🧪','Stick Merge','best_level',20,5,'medium'),
  ('stick_merge_best_level_25_140','Reach weapon level 25','Reach weapon level 25 in Stick Merge','🧪','Stick Merge','best_level',25,5,'medium'),
  ('stick_merge_best_score_100_141','100','Score 100 in Stick Merge','💥','Stick Merge','best_score',100,10,'hard'),
  ('stick_merge_best_score_250_142','250','Score 250 in Stick Merge','💥','Stick Merge','best_score',250,20,'crazy'),
  ('stick_merge_best_score_500_143','500','Score 500 in Stick Merge','💥','Stick Merge','best_score',500,20,'crazy'),
  ('stick_merge_best_score_1000_144','1000','Score 1000 in Stick Merge','💥','Stick Merge','best_score',1000,20,'crazy'),
  ('stick_merge_best_score_2000_145','2000','Score 2000 in Stick Merge','💥','Stick Merge','best_score',2000,20,'crazy'),
  ('stick_merge_best_score_5000_146','5000','Score 5000 in Stick Merge','💥','Stick Merge','best_score',5000,20,'crazy'),
  ('stick_merge_best_score_10000_147','10000','Score 10000 in Stick Merge','💥','Stick Merge','best_score',10000,20,'crazy'),
  ('stick_merge_best_score_25000_148','25000','Score 25000 in Stick Merge','💥','Stick Merge','best_score',25000,20,'crazy'),
  ('drive_mad_best_level_3_149','Reach level 3','Reach level 3 in Drive Mad','🚗','Drive Mad','best_level',3,2,'not_so_hard'),
  ('drive_mad_best_level_5_150','Reach level 5','Reach level 5 in Drive Mad','🚗','Drive Mad','best_level',5,2,'not_so_hard'),
  ('drive_mad_best_level_10_151','Reach level 10','Reach level 10 in Drive Mad','🚗','Drive Mad','best_level',10,2,'not_so_hard'),
  ('drive_mad_best_level_15_152','Reach level 15','Reach level 15 in Drive Mad','🚗','Drive Mad','best_level',15,5,'medium'),
  ('drive_mad_best_level_20_153','Reach level 20','Reach level 20 in Drive Mad','🚗','Drive Mad','best_level',20,5,'medium'),
  ('drive_mad_best_level_25_154','Reach level 25','Reach level 25 in Drive Mad','🚗','Drive Mad','best_level',25,5,'medium'),
  ('drive_mad_best_level_30_155','Reach level 30','Reach level 30 in Drive Mad','🚗','Drive Mad','best_level',30,5,'medium'),
  ('drive_mad_best_level_40_156','Reach level 40','Reach level 40 in Drive Mad','🚗','Drive Mad','best_level',40,5,'medium'),
  ('drive_mad_best_level_50_157','Reach level 50','Reach level 50 in Drive Mad','🚗','Drive Mad','best_level',50,5,'medium'),
  ('drive_mad_best_level_75_158','Reach level 75','Reach level 75 in Drive Mad','🚗','Drive Mad','best_level',75,10,'hard'),
  ('drive_mad_best_level_100_159','Reach level 100','Reach level 100 in Drive Mad','🚗','Drive Mad','best_level',100,10,'hard'),
  ('run_3_best_level_3_160','Reach level 3','Reach level 3 in Run 3','🌌','Run 3','best_level',3,2,'not_so_hard'),
  ('run_3_best_level_5_161','Reach level 5','Reach level 5 in Run 3','🌌','Run 3','best_level',5,2,'not_so_hard'),
  ('run_3_best_level_10_162','Reach level 10','Reach level 10 in Run 3','🌌','Run 3','best_level',10,2,'not_so_hard'),
  ('run_3_best_level_15_163','Reach level 15','Reach level 15 in Run 3','🌌','Run 3','best_level',15,5,'medium'),
  ('run_3_best_level_20_164','Reach level 20','Reach level 20 in Run 3','🌌','Run 3','best_level',20,5,'medium'),
  ('run_3_best_level_30_165','Reach level 30','Reach level 30 in Run 3','🌌','Run 3','best_level',30,5,'medium'),
  ('run_3_best_level_40_166','Reach level 40','Reach level 40 in Run 3','🌌','Run 3','best_level',40,5,'medium'),
  ('run_3_best_level_50_167','Reach level 50','Reach level 50 in Run 3','🌌','Run 3','best_level',50,5,'medium'),
  ('run_3_best_level_75_168','Reach level 75','Reach level 75 in Run 3','🌌','Run 3','best_level',75,10,'hard'),
  ('run_3_best_level_100_169','Reach level 100','Reach level 100 in Run 3','🌌','Run 3','best_level',100,10,'hard'),
  ('google_doodle_baseball_hits_5_170','5 hits','Get 5 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',5,2,'not_so_hard'),
  ('google_doodle_baseball_hits_10_171','10 hits','Get 10 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',10,2,'not_so_hard'),
  ('google_doodle_baseball_hits_20_172','20 hits','Get 20 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',20,5,'medium'),
  ('google_doodle_baseball_hits_35_173','35 hits','Get 35 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',35,5,'medium'),
  ('google_doodle_baseball_hits_50_174','50 hits','Get 50 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',50,5,'medium'),
  ('google_doodle_baseball_hits_75_175','75 hits','Get 75 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',75,10,'hard'),
  ('google_doodle_baseball_hits_100_176','100 hits','Get 100 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',100,10,'hard'),
  ('google_doodle_baseball_hits_150_177','150 hits','Get 150 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',150,10,'hard'),
  ('google_doodle_baseball_hits_250_178','250 hits','Get 250 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',250,20,'crazy'),
  ('google_doodle_baseball_best_score_10_179','10','Score 10 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',10,2,'not_so_hard'),
  ('google_doodle_baseball_best_score_25_180','25','Score 25 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',25,5,'medium'),
  ('google_doodle_baseball_best_score_50_181','50','Score 50 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',50,5,'medium'),
  ('google_doodle_baseball_best_score_75_182','75','Score 75 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',75,10,'hard'),
  ('google_doodle_baseball_best_score_100_183','100','Score 100 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',100,10,'hard'),
  ('google_doodle_baseball_best_score_150_184','150','Score 150 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',150,10,'hard'),
  ('google_doodle_baseball_best_score_200_185','200','Score 200 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',200,20,'crazy'),
  ('google_doodle_baseball_best_score_300_186','300','Score 300 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',300,20,'crazy'),
  ('google_doodle_baseball_best_score_500_187','500','Score 500 in Google Doodle Baseball','🌭','Google Doodle Baseball','best_score',500,20,'crazy'),
  ('chess_com_wins_1_188','Win 1 Chess.com game(s)','Win 1 Chess.com game(s)','♜','Chess.com','wins',1,2,'not_so_hard'),
  ('chess_com_wins_3_189','Win 3 Chess.com game(s)','Win 3 Chess.com game(s)','♜','Chess.com','wins',3,5,'medium'),
  ('chess_com_wins_5_190','Win 5 Chess.com game(s)','Win 5 Chess.com game(s)','♜','Chess.com','wins',5,5,'medium'),
  ('chess_com_wins_10_191','Win 10 Chess.com game(s)','Win 10 Chess.com game(s)','♜','Chess.com','wins',10,10,'hard'),
  ('chess_com_wins_25_192','Win 25 Chess.com game(s)','Win 25 Chess.com game(s)','♜','Chess.com','wins',25,20,'crazy'),
  ('basket_random_best_score_315_193','Score 315 points in Basket Random','Score 315 points in Basket Random','🏀','Basket Random','best_score',315,20,'crazy'),
  ('tiny_fishing_fish_caught_525_194','Catch 525 fish in Tiny Fishing','Catch 525 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',525,20,'crazy'),
  ('chess_ai_checkmates_11_195','Checkmate the bot 11 times','Checkmate the bot 11 times','♛','Chess-AI','checkmates',11,10,'hard'),
  ('stick_merge_merges_410_196','Merge weapons 410 times in Stick Merge','Merge weapons 410 times in Stick Merge','🔫','Stick Merge','merges',410,20,'crazy'),
  ('drive_mad_best_level_55_197','Reach level 55 in Drive Mad','Reach level 55 in Drive Mad','🚗','Drive Mad','best_level',55,5,'medium'),
  ('run_3_best_level_55_198','Reach level 55 in Run 3','Reach level 55 in Run 3','🌌','Run 3','best_level',55,5,'medium'),
  ('google_doodle_baseball_hits_210_199','Get 210 hits in Google Doodle Baseball','Get 210 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',210,20,'crazy'),
  ('google_snake_best_score_550_200','Get 550 points in Google Snake','Get 550 points in Google Snake','🍎','Google Snake','best_score',550,20,'crazy'),
  ('slope_best_score_1100_201','Get 350 points in Slope','Get 350 points in one Slope round','🟢','Slope','best_score',350,10,'hard'),
  ('a_small_world_cup_wins_13_202','Win the World Cup 13 times','Win the World Cup 13 times','🏆','A Small World Cup','wins',13,10,'hard'),
  ('basket_random_best_score_330_203','Score 330 points in Basket Random','Score 330 points in Basket Random','🏀','Basket Random','best_score',330,20,'crazy'),
  ('tiny_fishing_fish_caught_550_204','Catch 550 fish in Tiny Fishing','Catch 550 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',550,20,'crazy'),
  ('chess_ai_checkmates_12_205','Checkmate the bot 12 times','Checkmate the bot 12 times','♛','Chess-AI','checkmates',12,10,'hard'),
  ('stick_merge_merges_430_206','Merge weapons 430 times in Stick Merge','Merge weapons 430 times in Stick Merge','🔫','Stick Merge','merges',430,20,'crazy'),
  ('drive_mad_best_level_60_207','Reach level 60 in Drive Mad','Reach level 60 in Drive Mad','🚗','Drive Mad','best_level',60,5,'medium'),
  ('run_3_best_level_60_208','Reach level 60 in Run 3','Reach level 60 in Run 3','🌌','Run 3','best_level',60,5,'medium'),
  ('google_doodle_baseball_hits_220_209','Get 220 hits in Google Doodle Baseball','Get 220 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',220,20,'crazy'),
  ('google_snake_best_score_575_210','Get 575 points in Google Snake','Get 575 points in Google Snake','🍎','Google Snake','best_score',575,20,'crazy'),
  ('slope_best_score_1150_211','Get 400 points in Slope','Get 400 points in one Slope round','🟢','Slope','best_score',400,20,'crazy'),
  ('a_small_world_cup_wins_13_212','Win the World Cup 13 times','Win the World Cup 13 times','🏆','A Small World Cup','wins',13,10,'hard'),
  ('basket_random_best_score_345_213','Score 345 points in Basket Random','Score 345 points in Basket Random','🏀','Basket Random','best_score',345,20,'crazy'),
  ('tiny_fishing_fish_caught_575_214','Catch 575 fish in Tiny Fishing','Catch 575 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',575,20,'crazy'),
  ('chess_ai_checkmates_12_215','Checkmate the bot 12 times','Checkmate the bot 12 times','♛','Chess-AI','checkmates',12,10,'hard'),
  ('stick_merge_merges_450_216','Merge weapons 450 times in Stick Merge','Merge weapons 450 times in Stick Merge','🔫','Stick Merge','merges',450,20,'crazy'),
  ('drive_mad_best_level_60_217','Reach level 60 in Drive Mad','Reach level 60 in Drive Mad','🚗','Drive Mad','best_level',60,5,'medium'),
  ('run_3_best_level_60_218','Reach level 60 in Run 3','Reach level 60 in Run 3','🌌','Run 3','best_level',60,5,'medium'),
  ('google_doodle_baseball_hits_230_219','Get 230 hits in Google Doodle Baseball','Get 230 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',230,20,'crazy'),
  ('google_snake_best_score_600_220','Get 600 points in Google Snake','Get 600 points in Google Snake','🍎','Google Snake','best_score',600,20,'crazy'),
  ('slope_best_score_1200_221','Get 500 points in Slope','Get 500 points in one Slope round','🟢','Slope','best_score',500,20,'crazy'),
  ('a_small_world_cup_wins_14_222','Win the World Cup 14 times','Win the World Cup 14 times','🏆','A Small World Cup','wins',14,10,'hard'),
  ('basket_random_best_score_360_223','Score 360 points in Basket Random','Score 360 points in Basket Random','🏀','Basket Random','best_score',360,20,'crazy'),
  ('tiny_fishing_fish_caught_600_224','Catch 600 fish in Tiny Fishing','Catch 600 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',600,20,'crazy'),
  ('chess_ai_checkmates_13_225','Checkmate the bot 13 times','Checkmate the bot 13 times','♛','Chess-AI','checkmates',13,10,'hard'),
  ('stick_merge_merges_470_226','Merge weapons 470 times in Stick Merge','Merge weapons 470 times in Stick Merge','🔫','Stick Merge','merges',470,20,'crazy'),
  ('drive_mad_best_level_65_227','Reach level 65 in Drive Mad','Reach level 65 in Drive Mad','🚗','Drive Mad','best_level',65,5,'medium'),
  ('run_3_best_level_65_228','Reach level 65 in Run 3','Reach level 65 in Run 3','🌌','Run 3','best_level',65,5,'medium'),
  ('google_doodle_baseball_hits_240_229','Get 240 hits in Google Doodle Baseball','Get 240 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',240,20,'crazy'),
  ('google_snake_best_score_625_230','Get 625 points in Google Snake','Get 625 points in Google Snake','🍎','Google Snake','best_score',625,20,'crazy'),
  ('slope_best_score_1250_231','Get 650 points in Slope','Get 650 points in one Slope round','🟢','Slope','best_score',650,20,'crazy'),
  ('a_small_world_cup_wins_14_232','Win the World Cup 14 times','Win the World Cup 14 times','🏆','A Small World Cup','wins',14,10,'hard'),
  ('basket_random_best_score_375_233','Score 375 points in Basket Random','Score 375 points in Basket Random','🏀','Basket Random','best_score',375,20,'crazy'),
  ('tiny_fishing_fish_caught_625_234','Catch 625 fish in Tiny Fishing','Catch 625 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',625,20,'crazy'),
  ('chess_ai_checkmates_13_235','Checkmate the bot 13 times','Checkmate the bot 13 times','♛','Chess-AI','checkmates',13,10,'hard'),
  ('stick_merge_merges_490_236','Merge weapons 490 times in Stick Merge','Merge weapons 490 times in Stick Merge','🔫','Stick Merge','merges',490,20,'crazy'),
  ('drive_mad_best_level_65_237','Reach level 65 in Drive Mad','Reach level 65 in Drive Mad','🚗','Drive Mad','best_level',65,5,'medium'),
  ('run_3_best_level_65_238','Reach level 65 in Run 3','Reach level 65 in Run 3','🌌','Run 3','best_level',65,5,'medium'),
  ('google_doodle_baseball_hits_250_239','Get 250 hits in Google Doodle Baseball','Get 250 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',250,20,'crazy'),
  ('google_snake_best_score_650_240','Get 650 points in Google Snake','Get 650 points in Google Snake','🍎','Google Snake','best_score',650,20,'crazy'),
  ('slope_best_score_1300_241','Get 800 points in Slope','Get 800 points in one Slope round','🟢','Slope','best_score',800,20,'crazy'),
  ('a_small_world_cup_wins_15_242','Win the World Cup 15 times','Win the World Cup 15 times','🏆','A Small World Cup','wins',15,20,'crazy'),
  ('basket_random_best_score_390_243','Score 390 points in Basket Random','Score 390 points in Basket Random','🏀','Basket Random','best_score',390,20,'crazy'),
  ('tiny_fishing_fish_caught_650_244','Catch 650 fish in Tiny Fishing','Catch 650 fish in Tiny Fishing','🎣','Tiny Fishing','fish_caught',650,20,'crazy'),
  ('chess_ai_checkmates_14_245','Checkmate the bot 14 times','Checkmate the bot 14 times','♛','Chess-AI','checkmates',14,10,'hard'),
  ('stick_merge_merges_510_246','Merge weapons 510 times in Stick Merge','Merge weapons 510 times in Stick Merge','🔫','Stick Merge','merges',510,20,'crazy'),
  ('drive_mad_best_level_70_247','Reach level 70 in Drive Mad','Reach level 70 in Drive Mad','🚗','Drive Mad','best_level',70,5,'medium'),
  ('run_3_best_level_70_248','Reach level 70 in Run 3','Reach level 70 in Run 3','🌌','Run 3','best_level',70,5,'medium'),
  ('google_doodle_baseball_hits_260_249','Get 260 hits in Google Doodle Baseball','Get 260 hits in Google Doodle Baseball','⚾','Google Doodle Baseball','hits',260,20,'crazy')
on conflict (achievement_id) do update set
  title=excluded.title,
  description=excluded.description,
  icon=excluded.icon,
  game_title=excluded.game_title,
  stat=excluded.stat,
  target=excluded.target,
  reward_points=excluded.reward_points,
  difficulty=excluded.difficulty;

alter table public.game_stats enable row level security;
alter table public.user_achievements enable row level security;
alter table public.achievement_catalog enable row level security;

drop policy if exists "game_stats_select_own" on public.game_stats;
drop policy if exists "game_stats_insert_own" on public.game_stats;
drop policy if exists "game_stats_update_own" on public.game_stats;
create policy "game_stats_select_own" on public.game_stats for select to authenticated using (user_id = auth.uid() or public.is_blank_space_admin());
create policy "game_stats_insert_own" on public.game_stats for insert to authenticated with check (user_id = auth.uid());
create policy "game_stats_update_own" on public.game_stats for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_achievements_select_own_or_admin" on public.user_achievements;
drop policy if exists "user_achievements_insert_own" on public.user_achievements;
drop policy if exists "user_achievements_update_own" on public.user_achievements;
create policy "user_achievements_select_own_or_admin" on public.user_achievements for select to authenticated using (user_id = auth.uid() or public.is_blank_space_admin());
create policy "user_achievements_insert_own" on public.user_achievements for insert to authenticated with check (user_id = auth.uid());
create policy "user_achievements_update_own" on public.user_achievements for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "achievement_catalog_read" on public.achievement_catalog;
create policy "achievement_catalog_read" on public.achievement_catalog for select to anon, authenticated using (true);

grant select, insert, update on table public.game_stats to authenticated;
grant select, insert, update on table public.user_achievements to authenticated;
grant select on table public.achievement_catalog to anon, authenticated;

drop function if exists public.award_ready_achievements(uuid, text);
create function public.award_ready_achievements(p_user_id uuid, p_game_title text default null)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_awards integer := 0;
  v_points integer := 0;
begin
  with eligible as (
    select c.*
    from public.achievement_catalog c
    join public.game_stats gs on gs.user_id = p_user_id and gs.game_title = c.game_title
    where (p_game_title is null or c.game_title = p_game_title)
      and case c.stat
        when 'play_count' then gs.play_count
        when 'best_score' then gs.best_score
        when 'goals' then gs.goals
        when 'wins' then gs.wins
        when 'fish_caught' then gs.fish_caught
        when 'money_earned' then gs.money_earned
        when 'checks' then gs.checks
        when 'checkmates' then gs.checkmates
        when 'merges' then gs.merges
        when 'best_level' then gs.best_level
        when 'hits' then gs.hits
        else 0 end >= c.target
  ), inserted as (
    insert into public.user_achievements(user_id, achievement_id, title, description, icon, game_title, reward_points)
    select p_user_id, achievement_id, title, description, icon, game_title, reward_points
    from eligible
    on conflict (user_id, achievement_id) do nothing
    returning reward_points
  )
  select count(*), coalesce(sum(reward_points),0) into v_awards, v_points from inserted;

  if v_awards > 0 then
    perform set_config('blank_space.allow_points_update','1',true);
    update public.profiles set points = coalesce(points,0) + v_points where id = p_user_id;
  end if;
  return coalesce(v_awards,0);
end;
$$;

grant execute on function public.award_ready_achievements(uuid, text) to authenticated;

drop function if exists public.record_game_progress(text, boolean, integer);
create function public.record_game_progress(p_game_title text, p_open_event boolean default false, p_seconds integer default 0)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_game_title text := trim(coalesce(p_game_title,''));
  v_new_awards integer := 0;
  v_stat jsonb;
begin
  if v_uid is null then raise exception 'Not signed in.'; end if;
  if v_game_title = '' then raise exception 'Game title is required.'; end if;
  insert into public.game_stats(user_id,game_title,play_count,play_seconds)
  values(v_uid,v_game_title,case when coalesce(p_open_event,false) then 1 else 0 end,greatest(0,coalesce(p_seconds,0)))
  on conflict(user_id,game_title) do update set
    play_count=coalesce(public.game_stats.play_count,0)+excluded.play_count,
    play_seconds=coalesce(public.game_stats.play_seconds,0)+excluded.play_seconds,
    last_played_at=now();
  v_new_awards := public.award_ready_achievements(v_uid, v_game_title);
  select to_jsonb(gs) || jsonb_build_object('new_awards', v_new_awards) into v_stat from public.game_stats gs where gs.user_id=v_uid and gs.game_title=v_game_title;
  return coalesce(v_stat,'{}'::jsonb);
end;
$$;

drop function if exists public.record_game_metric(text, text, integer, text);
create function public.record_game_metric(p_game_title text, p_metric text, p_value integer default 1, p_mode text default 'max')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_game_title text := trim(coalesce(p_game_title,''));
  v_metric text := lower(trim(coalesce(p_metric,'')));
  v_mode text := lower(trim(coalesce(p_mode,'max')));
  v_value integer := greatest(0, coalesce(p_value,0));
  v_new_awards integer := 0;
  v_stat jsonb;
begin
  if v_uid is null then raise exception 'Not signed in.'; end if;
  if v_game_title = '' then raise exception 'Game title is required.'; end if;
  insert into public.game_stats(user_id,game_title) values(v_uid,v_game_title) on conflict(user_id,game_title) do nothing;

  if v_metric = 'best_score' then
    update public.game_stats set best_score = case when v_mode='replace' then v_value when v_mode='add' then coalesce(best_score,0)+greatest(v_value,1) else greatest(coalesce(best_score,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'goals' then
    update public.game_stats set goals = case when v_mode='replace' then v_value when v_mode='add' then coalesce(goals,0)+greatest(v_value,1) else greatest(coalesce(goals,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'wins' then
    update public.game_stats set wins = case when v_mode='replace' then v_value when v_mode='add' then coalesce(wins,0)+greatest(v_value,1) else greatest(coalesce(wins,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'fish_caught' then
    update public.game_stats set fish_caught = case when v_mode='replace' then v_value when v_mode='add' then coalesce(fish_caught,0)+greatest(v_value,1) else greatest(coalesce(fish_caught,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'money_earned' then
    update public.game_stats set money_earned = case when v_mode='replace' then v_value when v_mode='add' then coalesce(money_earned,0)+greatest(v_value,1) else greatest(coalesce(money_earned,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'checks' then
    update public.game_stats set checks = case when v_mode='replace' then v_value when v_mode='add' then coalesce(checks,0)+greatest(v_value,1) else greatest(coalesce(checks,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'checkmates' then
    update public.game_stats set checkmates = case when v_mode='replace' then v_value when v_mode='add' then coalesce(checkmates,0)+greatest(v_value,1) else greatest(coalesce(checkmates,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'merges' then
    update public.game_stats set merges = case when v_mode='replace' then v_value when v_mode='add' then coalesce(merges,0)+greatest(v_value,1) else greatest(coalesce(merges,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'best_level' then
    update public.game_stats set best_level = case when v_mode='replace' then v_value when v_mode='add' then coalesce(best_level,0)+greatest(v_value,1) else greatest(coalesce(best_level,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  elsif v_metric = 'hits' then
    update public.game_stats set hits = case when v_mode='replace' then v_value when v_mode='add' then coalesce(hits,0)+greatest(v_value,1) else greatest(coalesce(hits,0),v_value) end, last_played_at=now() where user_id=v_uid and game_title=v_game_title;
  else
    raise exception 'Unknown game metric: %', v_metric;
  end if;

  v_new_awards := public.award_ready_achievements(v_uid, v_game_title);
  select to_jsonb(gs) || jsonb_build_object('new_awards', v_new_awards) into v_stat from public.game_stats gs where gs.user_id=v_uid and gs.game_title=v_game_title;
  return coalesce(v_stat,'{}'::jsonb);
end;
$$;

drop function if exists public.award_achievement(text, text, text, text, text, integer);
create function public.award_achievement(p_achievement_id text, p_title text, p_description text, p_icon text, p_game_title text default null, p_reward_points integer default 0)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_count integer := 0;
  v_points integer := greatest(0, least(coalesce(p_reward_points,0), 10000));
begin
  if v_uid is null then raise exception 'Not signed in.'; end if;
  insert into public.user_achievements(user_id, achievement_id, title, description, icon, game_title, reward_points)
  values(v_uid, left(trim(coalesce(p_achievement_id,'')),120), left(trim(coalesce(p_title,'Achievement')),120), left(coalesce(p_description,''),300), left(coalesce(nullif(trim(p_icon),''),'🏆'),32), p_game_title, v_points)
  on conflict(user_id, achievement_id) do nothing;
  get diagnostics v_count = row_count;
  if v_count > 0 then
    perform set_config('blank_space.allow_points_update','1',true);
    update public.profiles set points = coalesce(points,0) + v_points where id = v_uid;
    return true;
  end if;
  return false;
end;
$$;

grant execute on function public.record_game_metric(text, text, integer, text) to authenticated;
grant execute on function public.record_game_progress(text, boolean, integer) to authenticated;
grant execute on function public.award_achievement(text, text, text, text, text, integer) to authenticated;

-- Leaderboard now includes rank.
drop function if exists public.get_public_leaderboard(integer);
create function public.get_public_leaderboard(max_rows integer default 100)
returns table(id uuid, username text, avatar_url text, points integer, equipped_icon text, rank text)
language sql
security definer
set search_path = public
as $$
  select p.id, p.username, p.avatar_url, p.points, p.equipped_icon, coalesce(p.rank,'member') as rank
  from public.profiles p
  order by p.points desc, lower(p.username) asc
  limit greatest(1, least(coalesce(max_rows,100),100));
$$;

grant execute on function public.get_public_leaderboard(integer) to anon, authenticated;

select pg_notify('pgrst', 'reload schema');
-- Done: v89 database update completed without resetting points or accounts.
