-- Blank Space v97: Fix Owner Panel "Send to everyone" timed messages
-- Paste this whole file into Supabase SQL Editor and click Run.
--
-- This fixes the backend for Timed Message sending to everyone.
-- It also keeps a fallback: if an older website still calls admin_send_user_message_v93,
-- typing "everyone" or "all" in the username box will send to everyone.
--
-- The actual checkbox validation is website code, so upload Blank Space v97.zip too.

create table if not exists public.admin_actions_log (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_username text,
  action text not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_user_messages (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  admin_id uuid references public.profiles(id) on delete set null,
  title text default 'Blank Space Notice',
  message text not null,
  style text not null default 'notice',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '20 seconds')
);

alter table public.admin_user_messages add column if not exists title text default 'Blank Space Notice';
alter table public.admin_user_messages add column if not exists style text not null default 'notice';
alter table public.admin_user_messages add column if not exists active boolean not null default true;
alter table public.admin_user_messages add column if not exists created_at timestamptz not null default now();
alter table public.admin_user_messages add column if not exists expires_at timestamptz not null default (now() + interval '20 seconds');

create index if not exists admin_user_messages_target_active_idx
on public.admin_user_messages(target_user_id, active, expires_at desc);

create or replace function public.is_blank_space_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(trim(coalesce(p.rank, 'member'))) in ('owner', 'admin')
  )
  or exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
  );
$$;

grant execute on function public.is_blank_space_admin() to anon, authenticated;

alter table public.admin_user_messages enable row level security;

drop policy if exists admin_messages_select_v97 on public.admin_user_messages;
drop policy if exists admin_messages_select_v95 on public.admin_user_messages;

create policy admin_messages_select_v97
on public.admin_user_messages
for select
to authenticated
using (target_user_id = auth.uid() or public.is_blank_space_admin());

grant select on table public.admin_user_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- New fixed function used by Blank Space v97.
drop function if exists public.admin_send_user_message_v95(text, text, integer, text, boolean);

create function public.admin_send_user_message_v95(
  p_username text,
  p_message text,
  p_seconds integer default 20,
  p_style text default 'notice',
  p_send_all boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid := auth.uid();
  v_target public.profiles%rowtype;
  v_seconds integer := greatest(3, least(coalesce(p_seconds, 20), 3600));
  v_style text := lower(trim(coalesce(p_style, 'notice')));
  v_message text := left(trim(coalesce(p_message, '')), 500);
  v_username text := lower(trim(coalesce(p_username, '')));
  v_count integer := 0;
begin
  if v_admin_id is null or not public.is_blank_space_admin() then
    raise exception 'Owner/Admin only.';
  end if;

  if v_message = '' then
    raise exception 'Message is required.';
  end if;

  if v_style not in ('notice', 'warning', 'danger') then
    v_style := 'notice';
  end if;

  -- Send to everyone when the checkbox is used OR when an older UI sends a special username.
  if coalesce(p_send_all, false) or v_username in ('everyone', 'all', 'all users', '*') then
    insert into public.admin_user_messages(target_user_id, admin_id, title, message, style, active, expires_at)
    select id, v_admin_id, 'Blank Space Notice', v_message, v_style, true, now() + make_interval(secs => v_seconds)
    from public.profiles;

    get diagnostics v_count = row_count;

    insert into public.admin_actions_log(admin_id, target_user_id, target_username, action, reason)
    values(v_admin_id, null, 'ALL USERS', 'timed_message_all', left(v_message, 240));

    return jsonb_build_object('ok', true, 'all', true, 'sent_to', v_count, 'seconds', v_seconds, 'style', v_style);
  end if;

  if v_username = '' then
    raise exception 'Username is required unless Send to everyone is checked.';
  end if;

  select * into v_target
  from public.profiles
  where lower(trim(username)) = v_username
  order by created_at asc nulls last, id asc
  limit 1;

  if v_target.id is null then
    raise exception 'User not found.';
  end if;

  insert into public.admin_user_messages(target_user_id, admin_id, title, message, style, active, expires_at)
  values(v_target.id, v_admin_id, 'Blank Space Notice', v_message, v_style, true, now() + make_interval(secs => v_seconds));

  insert into public.admin_actions_log(admin_id, target_user_id, target_username, action, reason)
  values(v_admin_id, v_target.id, v_target.username, 'timed_message', left(v_message, 240));

  return jsonb_build_object('ok', true, 'all', false, 'sent_to', 1, 'target_username', v_target.username, 'seconds', v_seconds, 'style', v_style);
end;
$$;

grant execute on function public.admin_send_user_message_v95(text, text, integer, text, boolean) to authenticated;

-- Backward-compatible v93 function. Older site code can send to everyone by using username "everyone".
drop function if exists public.admin_send_user_message_v93(text, text, integer, text);

create function public.admin_send_user_message_v93(
  p_username text,
  p_message text,
  p_seconds integer default 20,
  p_style text default 'notice'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := lower(trim(coalesce(p_username, '')));
begin
  return public.admin_send_user_message_v95(
    p_username,
    p_message,
    p_seconds,
    p_style,
    v_username in ('everyone', 'all', 'all users', '*')
  );
end;
$$;

grant execute on function public.admin_send_user_message_v93(text, text, integer, text) to authenticated;

-- Realtime registration, ignore if already added.
do $$
begin
  begin
    alter publication supabase_realtime add table public.admin_user_messages;
  exception when others then null;
  end;
end $$;

drop function if exists public.blank_space_v97_timed_message_healthcheck();

create function public.blank_space_v97_timed_message_healthcheck()
returns table(check_name text, result text)
language sql
security definer
set search_path = public
as $$
  select 'admin_user_messages_table', case when to_regclass('public.admin_user_messages') is not null then 'installed' else 'missing' end
  union all
  select 'v95_send_function', 'installed'
  union all
  select 'v93_compat_function', 'installed'
  union all
  select 'status', 'OK - backend supports Send to everyone; upload v97 website for the checkbox fix';
$$;

grant execute on function public.blank_space_v97_timed_message_healthcheck() to anon, authenticated;

select pg_notify('pgrst', 'reload schema');
select * from public.blank_space_v97_timed_message_healthcheck();
