-- Blank Space v84 Supabase update
-- Safe update: achievement debug/testing support and admin panel support.
-- This does NOT delete accounts, friends, messages, suggestions, icons, trades, achievements, or points.

-- Blank Space v82 Supabase update
-- Safe update: adds stronger achievement metrics, Chat unread counts, and fixes function replacement errors.
-- This does NOT delete existing accounts, points, friends, messages, suggestions, or achievements.

alter table public.profiles
  add column if not exists equipped_icon text,
  add column if not exists equipped_achievement_id text,
  add column if not exists points integer not null default 0;

create table if not exists public.game_stats (
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_title text not null,
  play_count integer not null default 0,
  play_seconds integer not null default 0,
  first_played_at timestamptz not null default now(),
  last_played_at timestamptz not null default now(),
  primary key (user_id, game_title),
  constraint game_stats_title_length check (char_length(game_title) between 1 and 120)
);

alter table public.game_stats
  add column if not exists best_score integer not null default 0,
  add column if not exists goals integer not null default 0,
  add column if not exists wins integer not null default 0,
  add column if not exists fish_caught integer not null default 0,
  add column if not exists money_earned integer not null default 0,
  add column if not exists checks integer not null default 0,
  add column if not exists checkmates integer not null default 0,
  add column if not exists merges integer not null default 0,
  add column if not exists best_level integer not null default 0,
  add column if not exists hits integer not null default 0;

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id text not null,
  title text not null,
  description text not null,
  icon text not null,
  game_title text,
  reward_points integer not null default 0,
  earned_at timestamptz not null default now(),
  primary key (user_id, achievement_id),
  constraint achievement_id_length check (char_length(achievement_id) between 2 and 80),
  constraint achievement_title_length check (char_length(title) between 2 and 80),
  constraint achievement_description_length check (char_length(description) between 2 and 240),
  constraint achievement_icon_length check (char_length(icon) between 1 and 16),
  constraint achievement_reward_nonnegative check (reward_points >= 0 and reward_points <= 10000)
);

create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friends(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint friend_messages_body_length check (char_length(body) between 1 and 500)
);

alter table public.friend_messages
  add column if not exists read_at timestamptz;

create index if not exists friend_messages_friendship_created_idx
on public.friend_messages (friendship_id, created_at);

create index if not exists friend_messages_unread_idx
on public.friend_messages (friendship_id, sender_id, read_at);

alter table public.game_stats enable row level security;
alter table public.user_achievements enable row level security;
alter table public.friend_messages enable row level security;

-- RLS policies for game stats
drop policy if exists "game_stats_select_own" on public.game_stats;
drop policy if exists "game_stats_insert_own" on public.game_stats;
drop policy if exists "game_stats_update_own" on public.game_stats;

create policy "game_stats_select_own"
on public.game_stats
for select
to authenticated
using (user_id = auth.uid() or public.is_blank_space_admin());

create policy "game_stats_insert_own"
on public.game_stats
for insert
to authenticated
with check (user_id = auth.uid());

create policy "game_stats_update_own"
on public.game_stats
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- RLS policies for achievements
drop policy if exists "user_achievements_select_own_or_admin" on public.user_achievements;
drop policy if exists "user_achievements_insert_own" on public.user_achievements;
drop policy if exists "user_achievements_update_own" on public.user_achievements;

create policy "user_achievements_select_own_or_admin"
on public.user_achievements
for select
to authenticated
using (user_id = auth.uid() or public.is_blank_space_admin());

create policy "user_achievements_insert_own"
on public.user_achievements
for insert
to authenticated
with check (user_id = auth.uid());

create policy "user_achievements_update_own"
on public.user_achievements
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- RLS policies for friend chat, safe to re-run.
drop policy if exists "friend_messages_select_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_insert_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_update_read_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_delete_sender_or_admin" on public.friend_messages;

create policy "friend_messages_select_own_friendship"
on public.friend_messages
for select
to authenticated
using (
  exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_insert_own_friendship"
on public.friend_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_update_read_own_friendship"
on public.friend_messages
for update
to authenticated
using (
  sender_id <> auth.uid()
  and exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
)
with check (
  exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_delete_sender_or_admin"
on public.friend_messages
for delete
to authenticated
using (sender_id = auth.uid() or public.is_blank_space_admin());

-- Drop old function signatures before recreating functions with wider return columns.
drop function if exists public.record_game_progress(text, boolean, integer);
drop function if exists public.record_game_metric(text, text, integer, text);
drop function if exists public.get_public_leaderboard(integer);

-- Record reliable website-side game progress plus return all metric columns.
create function public.record_game_progress(
  p_game_title text,
  p_open_event boolean default false,
  p_seconds integer default 0
)
returns table (
  game_title text,
  play_count integer,
  play_seconds integer,
  best_score integer,
  goals integer,
  wins integer,
  fish_caught integer,
  money_earned integer,
  checks integer,
  checkmates integer,
  merges integer,
  best_level integer,
  hits integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  add_count integer := case when coalesce(p_open_event, false) then 1 else 0 end;
  add_seconds integer := greatest(0, coalesce(p_seconds, 0));
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  if p_game_title is null or char_length(trim(p_game_title)) < 1 then
    raise exception 'Game title is required.';
  end if;

  insert into public.game_stats (user_id, game_title, play_count, play_seconds)
  values (uid, trim(p_game_title), add_count, add_seconds)
  on conflict (user_id, game_title)
  do update set
    play_count = public.game_stats.play_count + excluded.play_count,
    play_seconds = public.game_stats.play_seconds + excluded.play_seconds,
    last_played_at = now();

  return query
  select gs.game_title, gs.play_count, gs.play_seconds, gs.best_score, gs.goals, gs.wins,
         gs.fish_caught, gs.money_earned, gs.checks, gs.checkmates, gs.merges, gs.best_level, gs.hits
  from public.game_stats gs
  where gs.user_id = uid and gs.game_title = trim(p_game_title);
end;
$$;

grant execute on function public.record_game_progress(text, boolean, integer) to authenticated;

-- Record score/win/goal/catch/check/merge metrics sent by self-hosted games.
create function public.record_game_metric(
  p_game_title text,
  p_metric text,
  p_value integer default 1,
  p_mode text default 'max'
)
returns table (
  game_title text,
  play_count integer,
  play_seconds integer,
  best_score integer,
  goals integer,
  wins integer,
  fish_caught integer,
  money_earned integer,
  checks integer,
  checkmates integer,
  merges integer,
  best_level integer,
  hits integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  metric text := lower(trim(coalesce(p_metric, '')));
  val integer := greatest(0, coalesce(p_value, 0));
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;
  if p_game_title is null or char_length(trim(p_game_title)) < 1 then
    raise exception 'Game title is required.';
  end if;

  insert into public.game_stats (user_id, game_title)
  values (uid, trim(p_game_title))
  on conflict (user_id, game_title) do nothing;

  if metric = 'best_score' then
    update public.game_stats set best_score = greatest(best_score, val), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'goals' then
    update public.game_stats set goals = goals + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'wins' then
    update public.game_stats set wins = wins + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'fish_caught' then
    update public.game_stats set fish_caught = fish_caught + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'money_earned' then
    update public.game_stats set money_earned = greatest(money_earned, val), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'checks' then
    update public.game_stats set checks = checks + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'checkmates' then
    update public.game_stats set checkmates = checkmates + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'merges' then
    update public.game_stats set merges = merges + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'best_level' then
    update public.game_stats set best_level = greatest(best_level, val), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  elsif metric = 'hits' then
    update public.game_stats set hits = hits + greatest(val, 1), last_played_at = now() where user_id = uid and game_title = trim(p_game_title);
  else
    raise exception 'Unknown game metric: %', metric;
  end if;

  return query
  select gs.game_title, gs.play_count, gs.play_seconds, gs.best_score, gs.goals, gs.wins,
         gs.fish_caught, gs.money_earned, gs.checks, gs.checkmates, gs.merges, gs.best_level, gs.hits
  from public.game_stats gs
  where gs.user_id = uid and gs.game_title = trim(p_game_title);
end;
$$;

grant execute on function public.record_game_metric(text, text, integer, text) to authenticated;

-- Award an achievement once. If it is new, also adds reward points.
create or replace function public.award_achievement(
  p_achievement_id text,
  p_title text,
  p_description text,
  p_icon text,
  p_game_title text default null,
  p_reward_points integer default 0
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  inserted_count integer := 0;
  safe_points integer := greatest(0, least(coalesce(p_reward_points, 0), 10000));
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  insert into public.user_achievements (user_id, achievement_id, title, description, icon, game_title, reward_points)
  values (uid, p_achievement_id, p_title, p_description, p_icon, p_game_title, safe_points)
  on conflict (user_id, achievement_id) do nothing;

  get diagnostics inserted_count = row_count;

  if inserted_count > 0 then
    update public.profiles
    set points = coalesce(points, 0) + safe_points,
        equipped_icon = coalesce(equipped_icon, p_icon),
        equipped_achievement_id = coalesce(equipped_achievement_id, p_achievement_id)
    where id = uid;
    return true;
  end if;

  return false;
end;
$$;

grant execute on function public.award_achievement(text, text, text, text, text, integer) to authenticated;

create or replace function public.equip_achievement_icon(p_achievement_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  chosen_icon text;
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  select ua.icon into chosen_icon
  from public.user_achievements ua
  where ua.user_id = uid
    and ua.achievement_id = p_achievement_id;

  if chosen_icon is null then
    raise exception 'You have not unlocked that icon yet.';
  end if;

  update public.profiles
  set equipped_icon = chosen_icon,
      equipped_achievement_id = p_achievement_id
  where id = uid;
end;
$$;

grant execute on function public.equip_achievement_icon(text) to authenticated;

-- Public leaderboard includes equipped icon and still hides admins.
create function public.get_public_leaderboard(max_rows integer default 100)
returns table (
  id uuid,
  username text,
  avatar_url text,
  points integer,
  equipped_icon text
)
language sql
security definer
set search_path = public
as $$
  select p.id, p.username, p.avatar_url, p.points, p.equipped_icon
  from public.profiles p
  where not exists (
    select 1
    from public.admin_users a
    where a.user_id = p.id
  )
  order by p.points desc, lower(p.username) asc
  limit greatest(1, least(coalesce(max_rows, 100), 100));
$$;

grant execute on function public.get_public_leaderboard(integer) to anon, authenticated;

-- Corrected account deletion helper: handles whichever optional tables/columns exist.
create or replace function public.delete_rows_for_account_if_column_exists_v2(
  p_table_name text,
  p_column_name text,
  p_account_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_regclass(format('public.%I', p_table_name)) is not null
     and exists (
       select 1
       from information_schema.columns c
       where c.table_schema = 'public'
         and c.table_name = p_table_name
         and c.column_name = p_column_name
     )
  then
    execute format('delete from public.%I where %I = $1', p_table_name, p_column_name)
    using p_account_id;
  end if;
end;
$$;

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Not signed in.';
  end if;

  perform public.delete_rows_for_account_if_column_exists_v2('admin_users', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('admin_users', 'id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestion_reports', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestion_reports', 'reporter_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'profile_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'author_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('points_log', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('user_points', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('game_stats', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('user_achievements', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_messages', 'sender_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'sender_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'receiver_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'requester_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'addressee_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'from_user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friend_requests', 'to_user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'requester_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'receiver_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'user_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'friend_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'user1_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('friends', 'user2_id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('profiles', 'id', current_user_id);
  perform public.delete_rows_for_account_if_column_exists_v2('profiles', 'user_id', current_user_id);

  delete from auth.users where id = current_user_id;
end;
$$;

grant execute on function public.delete_my_account() to authenticated;
grant execute on function public.delete_rows_for_account_if_column_exists_v2(text, text, uuid) to authenticated;

-- Enable realtime for chat when available.
do $$
begin
  alter publication supabase_realtime add table public.friend_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;



-- Blank Space v83 Supabase update
-- Safe update: suggestions workflow, 250 achievements support, chat images, Icons/Trades, Admin Panel functions.
-- This does NOT delete existing accounts, friends, messages, suggestions, or achievements.

-- Suggestions: add in_works and admin comments.
alter table public.suggestions add column if not exists admin_comment text;
alter table public.suggestions add column if not exists decided_at timestamptz;
do $$ begin
  alter table public.suggestions drop constraint if exists suggestion_status_check;
exception when undefined_object then null; end $$;
alter table public.suggestions add constraint suggestion_status_check check (status in ('pending','in_works','approved','denied','rejected'));

create or replace function public.admin_set_suggestion_status_v83(
  suggestion_id_input bigint,
  new_status text,
  award_points integer default 0,
  admin_comment_input text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_suggestion public.suggestions%rowtype;
  previous_points integer;
  next_points integer;
  clean_comment text := nullif(left(coalesce(admin_comment_input, ''), 500), '');
begin
  if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
  if new_status not in ('pending','in_works','approved','denied','rejected') then raise exception 'Invalid suggestion status.'; end if;
  award_points := greatest(0, least(coalesce(award_points, 0), 10000));
  select * into old_suggestion from public.suggestions where id = suggestion_id_input for update;
  if not found then raise exception 'Suggestion not found.'; end if;
  previous_points := coalesce(old_suggestion.points_awarded, 0);
  next_points := case when new_status = 'approved' then award_points else 0 end;
  update public.profiles set points = greatest(0, coalesce(points,0) - previous_points + next_points) where id = old_suggestion.user_id;
  update public.suggestions set status = new_status, points_awarded = next_points, admin_comment = coalesce(clean_comment, admin_comment), decided_at = case when new_status in ('approved','denied','rejected') then now() else decided_at end where id = suggestion_id_input;
end;
$$;
grant execute on function public.admin_set_suggestion_status_v83(bigint, text, integer, text) to authenticated;

-- Chat images: data URL/text image support.
alter table public.friend_messages add column if not exists image_url text;
do $$ begin
  alter table public.friend_messages drop constraint if exists friend_messages_body_length;
exception when undefined_object then null; end $$;
alter table public.friend_messages add constraint friend_messages_body_length check (char_length(body) between 1 and 500);

-- Icon economy.
create table if not exists public.user_icons (
  user_id uuid not null references public.profiles(id) on delete cascade,
  icon_id text not null,
  icon text not null,
  name text not null,
  rarity text not null,
  acquired_at timestamptz not null default now(),
  primary key (user_id, icon_id),
  constraint user_icons_rarity_check check (rarity in ('common','uncommon','rare','epic','legendary','mythic','godly'))
);
alter table public.user_icons enable row level security;
drop policy if exists "user_icons_select_own_or_friends" on public.user_icons;
drop policy if exists "user_icons_insert_own" on public.user_icons;
drop policy if exists "user_icons_update_own" on public.user_icons;
delete from public.user_icons where icon_id is null;
create policy "user_icons_select_own_or_friends" on public.user_icons for select to authenticated using (
  user_id = auth.uid() or public.is_blank_space_admin() or exists (select 1 from public.friends f where f.status='accepted' and ((f.requester_id=auth.uid() and f.receiver_id=user_id) or (f.receiver_id=auth.uid() and f.requester_id=user_id)))
);
create policy "user_icons_insert_own" on public.user_icons for insert to authenticated with check (user_id = auth.uid());
create policy "user_icons_update_own" on public.user_icons for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create table if not exists public.icon_trades (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friends(id) on delete cascade,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  offered_icon_id text not null,
  requested_icon_id text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint icon_trades_status_check check (status in ('pending','accepted','rejected','cancelled'))
);
alter table public.icon_trades enable row level security;
drop policy if exists "icon_trades_select_own" on public.icon_trades;
drop policy if exists "icon_trades_insert_own" on public.icon_trades;
drop policy if exists "icon_trades_update_own" on public.icon_trades;
create policy "icon_trades_select_own" on public.icon_trades for select to authenticated using (requester_id=auth.uid() or receiver_id=auth.uid() or public.is_blank_space_admin());
create policy "icon_trades_insert_own" on public.icon_trades for insert to authenticated with check (requester_id=auth.uid());
create policy "icon_trades_update_own" on public.icon_trades for update to authenticated using (requester_id=auth.uid() or receiver_id=auth.uid() or public.is_blank_space_admin()) with check (requester_id=auth.uid() or receiver_id=auth.uid() or public.is_blank_space_admin());

create or replace function public.buy_icon_pack_v83(p_pack_id text, p_price integer, p_icon_id text, p_icon text, p_name text, p_rarity text)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); current_points integer; clean_price integer:=greatest(1,least(coalesce(p_price,5),1000));
begin
  if uid is null then raise exception 'Not signed in.'; end if;
  if p_rarity not in ('common','uncommon','rare','epic','legendary','mythic','godly') then raise exception 'Bad rarity.'; end if;
  select points into current_points from public.profiles where id=uid for update;
  if coalesce(current_points,0) < clean_price then raise exception 'Not enough points.'; end if;
  update public.profiles set points=points-clean_price where id=uid;
  insert into public.user_icons(user_id, icon_id, icon, name, rarity) values(uid, p_icon_id, p_icon, p_name, p_rarity)
  on conflict(user_id, icon_id) do update set acquired_at=now();
end; $$;
grant execute on function public.buy_icon_pack_v83(text, integer, text, text, text, text) to authenticated;

create or replace function public.equip_owned_icon_v83(p_icon_id text)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); chosen text;
begin
  if uid is null then raise exception 'Not signed in.'; end if;
  select icon into chosen from public.user_icons where user_id=uid and icon_id=p_icon_id;
  if chosen is null then raise exception 'You do not own that icon.'; end if;
  update public.profiles set equipped_icon=chosen, equipped_achievement_id=null where id=uid;
end; $$;
grant execute on function public.equip_owned_icon_v83(text) to authenticated;

create or replace function public.answer_icon_trade_v83(p_trade_id bigint, p_status text)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); tr public.icon_trades%rowtype; offered public.user_icons%rowtype; requested public.user_icons%rowtype;
begin
  if uid is null then raise exception 'Not signed in.'; end if;
  select * into tr from public.icon_trades where id=p_trade_id for update;
  if not found then raise exception 'Trade not found.'; end if;
  if tr.status <> 'pending' then raise exception 'Trade is already closed.'; end if;
  if p_status='cancelled' then
    if tr.requester_id <> uid and not public.is_blank_space_admin() then raise exception 'Only requester can cancel.'; end if;
    update public.icon_trades set status='cancelled', updated_at=now() where id=p_trade_id; return;
  elsif p_status='rejected' then
    if tr.receiver_id <> uid and not public.is_blank_space_admin() then raise exception 'Only receiver can deny.'; end if;
    update public.icon_trades set status='rejected', updated_at=now() where id=p_trade_id; return;
  elsif p_status='accepted' then
    if tr.receiver_id <> uid then raise exception 'Only receiver can accept.'; end if;
    select * into offered from public.user_icons where user_id=tr.requester_id and icon_id=tr.offered_icon_id for update;
    select * into requested from public.user_icons where user_id=tr.receiver_id and icon_id=tr.requested_icon_id for update;
    if offered.icon_id is null or requested.icon_id is null then raise exception 'One of the icons is no longer owned.'; end if;
    delete from public.user_icons where user_id=tr.requester_id and icon_id=tr.offered_icon_id;
    delete from public.user_icons where user_id=tr.receiver_id and icon_id=tr.requested_icon_id;
    insert into public.user_icons(user_id, icon_id, icon, name, rarity) values(tr.receiver_id, offered.icon_id, offered.icon, offered.name, offered.rarity) on conflict do nothing;
    insert into public.user_icons(user_id, icon_id, icon, name, rarity) values(tr.requester_id, requested.icon_id, requested.icon, requested.name, requested.rarity) on conflict do nothing;
    update public.icon_trades set status='accepted', updated_at=now() where id=p_trade_id; return;
  else raise exception 'Bad trade response.';
  end if;
end; $$;
grant execute on function public.answer_icon_trade_v83(bigint, text) to authenticated;

-- Admin panel functions.
create or replace function public.admin_change_username_v83(p_old_username text, p_new_username text)
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid;
begin
 if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
 if p_new_username !~ '^[A-Za-z0-9_]{3,20}$' then raise exception 'Invalid username.'; end if;
 select id into target_id from public.profiles where lower(username)=lower(trim(p_old_username));
 if target_id is null then raise exception 'User not found.'; end if;
 update public.profiles set username=trim(p_new_username), username_changed_at=now() where id=target_id;
end; $$;
grant execute on function public.admin_change_username_v83(text,text) to authenticated;

create or replace function public.admin_adjust_points_v83(p_username text, p_points integer, p_reason text default '')
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid; amount integer:=coalesce(p_points,0);
begin
 if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
 select id into target_id from public.profiles where lower(username)=lower(trim(p_username));
 if target_id is null then raise exception 'User not found.'; end if;
 update public.profiles set points=greatest(0, coalesce(points,0)+amount) where id=target_id;
end; $$;
grant execute on function public.admin_adjust_points_v83(text,integer,text) to authenticated;

create or replace function public.admin_delete_user_by_username_v83(p_username text)
returns void language plpgsql security definer set search_path=public, auth as $$
declare target_id uuid;
begin
 if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
 select id into target_id from public.profiles where lower(username)=lower(trim(p_username));
 if target_id is null then raise exception 'User not found.'; end if;
 perform public.delete_rows_for_account_if_column_exists_v2('admin_users', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('game_stats', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('user_achievements', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('user_icons', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('friend_messages', 'sender_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('friends', 'requester_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('friends', 'receiver_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('profiles', 'id', target_id);
 delete from auth.users where id=target_id;
end; $$;
grant execute on function public.admin_delete_user_by_username_v83(text) to authenticated;

-- Leaderboard function remains compatible.
drop function if exists public.get_public_leaderboard(integer);
create function public.get_public_leaderboard(max_rows integer default 100)
returns table (id uuid, username text, avatar_url text, points integer, equipped_icon text)
language sql security definer set search_path=public as $$
  select p.id, p.username, p.avatar_url, p.points, p.equipped_icon
  from public.profiles p
  where not exists (select 1 from public.admin_users a where a.user_id = p.id)
  order by p.points desc, lower(p.username) asc
  limit greatest(1, least(coalesce(max_rows,100),100));
$$;
grant execute on function public.get_public_leaderboard(integer) to anon, authenticated;




-- v84 compatibility grants and schema reload.
grant execute on function public.award_achievement(text, text, text, text, text, integer) to authenticated;
grant execute on function public.record_game_metric(text, text, integer, text) to authenticated;
grant execute on function public.record_game_progress(text, boolean, integer) to authenticated;
select pg_notify('pgrst', 'reload schema');
