-- Blank Space v79 Supabase update
-- Run this in Supabase SQL Editor before testing Blank Space v79.
-- Adds friend chat messages, account deletion, and clears the current website accounts
-- so old Mario/MarioAdmin browser-only accounts do not block the new username/password system.
-- WARNING: This intentionally deletes all current Blank Space accounts/profiles/suggestions/friends/messages.

-- 1) Friend chat table.
create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friends(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),

  constraint friend_messages_body_length check (char_length(body) between 1 and 500)
);

create index if not exists friend_messages_friendship_created_idx
on public.friend_messages (friendship_id, created_at);

alter table public.friend_messages enable row level security;

drop policy if exists "friend_messages_select_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_insert_own_friendship" on public.friend_messages;
drop policy if exists "friend_messages_delete_sender_or_admin" on public.friend_messages;

create policy "friend_messages_select_own_friendship"
on public.friend_messages
for select
to authenticated
using (
  exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_insert_own_friendship"
on public.friend_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.friends f
    where f.id = friendship_id
      and f.status = 'accepted'
      and (f.requester_id = auth.uid() or f.receiver_id = auth.uid())
  )
);

create policy "friend_messages_delete_sender_or_admin"
on public.friend_messages
for delete
to authenticated
using (sender_id = auth.uid() or public.is_blank_space_admin());

-- Enable Realtime for chat when available. If this notice says it already exists, that is fine.
do $$
begin
  alter publication supabase_realtime add table public.friend_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

-- 2) Account deletion RPC used by the Delete Account button.
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Not signed in.';
  end if;

  delete from public.friend_messages
  where sender_id = uid
     or friendship_id in (
       select id from public.friends
       where requester_id = uid or receiver_id = uid
     );

  delete from public.friends
  where requester_id = uid or receiver_id = uid;

  delete from public.suggestion_reports
  where user_id = uid
     or suggestion_id in (select id from public.suggestions where user_id = uid);

  delete from public.suggestions where user_id = uid;
  delete from public.admin_users where user_id = uid;
  delete from public.profiles where id = uid;

  -- Fully remove the Supabase Auth login when possible.
  delete from auth.users where id = uid;
end;
$$;

grant execute on function public.delete_my_account() to authenticated;

-- 3) Delete all current Blank Space accounts/data now, as requested.
-- This frees usernames like Mario and MarioAdmin so you can recreate them with the new username/password login.
create temporary table if not exists _blank_space_auth_users_to_delete as
select id from public.profiles;

delete from public.friend_messages;
delete from public.friends;
delete from public.suggestion_reports;
delete from public.suggestions;
delete from public.admin_users;
delete from public.profiles;

do $$
begin
  delete from auth.users
  where id in (select id from _blank_space_auth_users_to_delete);
exception
  when others then
    raise notice 'Blank Space public account data was cleared. Auth user cleanup was skipped: %', sqlerrm;
end $$;

drop table if exists _blank_space_auth_users_to_delete;

-- 4) Keep the public leaderboard function available after cleanup.
create or replace function public.get_public_leaderboard(max_rows integer default 100)
returns table (
  id uuid,
  username text,
  avatar_url text,
  points integer
)
language sql
security definer
set search_path = public
as $$
  select p.id, p.username, p.avatar_url, p.points
  from public.profiles p
  where not exists (
    select 1
    from public.admin_users a
    where a.user_id = p.id
  )
  order by p.points desc, lower(p.username) asc
  limit greatest(1, least(coalesce(max_rows, 100), 100));
$$;

grant execute on function public.get_public_leaderboard(integer) to anon, authenticated;
