
-- Blank Space v83 Supabase update
-- Safe update: suggestions workflow, 250 achievements support, chat images, Icons/Trades, Admin Panel functions.
-- This does NOT delete existing accounts, friends, messages, suggestions, or achievements.

-- Suggestions: add in_works and admin comments.
alter table public.suggestions add column if not exists admin_comment text;
alter table public.suggestions add column if not exists decided_at timestamptz;
do $$ begin
  alter table public.suggestions drop constraint if exists suggestion_status_check;
exception when undefined_object then null; end $$;
alter table public.suggestions add constraint suggestion_status_check check (status in ('pending','in_works','approved','denied','rejected'));

create or replace function public.admin_set_suggestion_status_v83(
  suggestion_id_input bigint,
  new_status text,
  award_points integer default 0,
  admin_comment_input text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_suggestion public.suggestions%rowtype;
  previous_points integer;
  next_points integer;
  clean_comment text := nullif(left(coalesce(admin_comment_input, ''), 500), '');
begin
  if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
  if new_status not in ('pending','in_works','approved','denied','rejected') then raise exception 'Invalid suggestion status.'; end if;
  award_points := greatest(0, least(coalesce(award_points, 0), 10000));
  select * into old_suggestion from public.suggestions where id = suggestion_id_input for update;
  if not found then raise exception 'Suggestion not found.'; end if;
  previous_points := coalesce(old_suggestion.points_awarded, 0);
  next_points := case when new_status = 'approved' then award_points else 0 end;
  update public.profiles set points = greatest(0, coalesce(points,0) - previous_points + next_points) where id = old_suggestion.user_id;
  update public.suggestions set status = new_status, points_awarded = next_points, admin_comment = coalesce(clean_comment, admin_comment), decided_at = case when new_status in ('approved','denied','rejected') then now() else decided_at end where id = suggestion_id_input;
end;
$$;
grant execute on function public.admin_set_suggestion_status_v83(bigint, text, integer, text) to authenticated;

-- Chat images: data URL/text image support.
alter table public.friend_messages add column if not exists image_url text;
do $$ begin
  alter table public.friend_messages drop constraint if exists friend_messages_body_length;
exception when undefined_object then null; end $$;
alter table public.friend_messages add constraint friend_messages_body_length check (char_length(body) between 1 and 500);

-- Icon economy.
create table if not exists public.user_icons (
  user_id uuid not null references public.profiles(id) on delete cascade,
  icon_id text not null,
  icon text not null,
  name text not null,
  rarity text not null,
  acquired_at timestamptz not null default now(),
  primary key (user_id, icon_id),
  constraint user_icons_rarity_check check (rarity in ('common','uncommon','rare','epic','legendary','mythic','godly'))
);
alter table public.user_icons enable row level security;
drop policy if exists "user_icons_select_own_or_friends" on public.user_icons;
drop policy if exists "user_icons_insert_own" on public.user_icons;
drop policy if exists "user_icons_update_own" on public.user_icons;
delete from public.user_icons where icon_id is null;
create policy "user_icons_select_own_or_friends" on public.user_icons for select to authenticated using (
  user_id = auth.uid() or public.is_blank_space_admin() or exists (select 1 from public.friends f where f.status='accepted' and ((f.requester_id=auth.uid() and f.receiver_id=user_id) or (f.receiver_id=auth.uid() and f.requester_id=user_id)))
);
create policy "user_icons_insert_own" on public.user_icons for insert to authenticated with check (user_id = auth.uid());
create policy "user_icons_update_own" on public.user_icons for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create table if not exists public.icon_trades (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friends(id) on delete cascade,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  offered_icon_id text not null,
  requested_icon_id text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint icon_trades_status_check check (status in ('pending','accepted','rejected','cancelled'))
);
alter table public.icon_trades enable row level security;
drop policy if exists "icon_trades_select_own" on public.icon_trades;
drop policy if exists "icon_trades_insert_own" on public.icon_trades;
drop policy if exists "icon_trades_update_own" on public.icon_trades;
create policy "icon_trades_select_own" on public.icon_trades for select to authenticated using (requester_id=auth.uid() or receiver_id=auth.uid() or public.is_blank_space_admin());
create policy "icon_trades_insert_own" on public.icon_trades for insert to authenticated with check (requester_id=auth.uid());
create policy "icon_trades_update_own" on public.icon_trades for update to authenticated using (requester_id=auth.uid() or receiver_id=auth.uid() or public.is_blank_space_admin()) with check (requester_id=auth.uid() or receiver_id=auth.uid() or public.is_blank_space_admin());

create or replace function public.buy_icon_pack_v83(p_pack_id text, p_price integer, p_icon_id text, p_icon text, p_name text, p_rarity text)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); current_points integer; clean_price integer:=greatest(1,least(coalesce(p_price,5),1000));
begin
  if uid is null then raise exception 'Not signed in.'; end if;
  if p_rarity not in ('common','uncommon','rare','epic','legendary','mythic','godly') then raise exception 'Bad rarity.'; end if;
  select points into current_points from public.profiles where id=uid for update;
  if coalesce(current_points,0) < clean_price then raise exception 'Not enough points.'; end if;
  update public.profiles set points=points-clean_price where id=uid;
  insert into public.user_icons(user_id, icon_id, icon, name, rarity) values(uid, p_icon_id, p_icon, p_name, p_rarity)
  on conflict(user_id, icon_id) do update set acquired_at=now();
end; $$;
grant execute on function public.buy_icon_pack_v83(text, integer, text, text, text, text) to authenticated;

create or replace function public.equip_owned_icon_v83(p_icon_id text)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); chosen text;
begin
  if uid is null then raise exception 'Not signed in.'; end if;
  select icon into chosen from public.user_icons where user_id=uid and icon_id=p_icon_id;
  if chosen is null then raise exception 'You do not own that icon.'; end if;
  update public.profiles set equipped_icon=chosen, equipped_achievement_id=null where id=uid;
end; $$;
grant execute on function public.equip_owned_icon_v83(text) to authenticated;

create or replace function public.answer_icon_trade_v83(p_trade_id bigint, p_status text)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); tr public.icon_trades%rowtype; offered public.user_icons%rowtype; requested public.user_icons%rowtype;
begin
  if uid is null then raise exception 'Not signed in.'; end if;
  select * into tr from public.icon_trades where id=p_trade_id for update;
  if not found then raise exception 'Trade not found.'; end if;
  if tr.status <> 'pending' then raise exception 'Trade is already closed.'; end if;
  if p_status='cancelled' then
    if tr.requester_id <> uid and not public.is_blank_space_admin() then raise exception 'Only requester can cancel.'; end if;
    update public.icon_trades set status='cancelled', updated_at=now() where id=p_trade_id; return;
  elsif p_status='rejected' then
    if tr.receiver_id <> uid and not public.is_blank_space_admin() then raise exception 'Only receiver can deny.'; end if;
    update public.icon_trades set status='rejected', updated_at=now() where id=p_trade_id; return;
  elsif p_status='accepted' then
    if tr.receiver_id <> uid then raise exception 'Only receiver can accept.'; end if;
    select * into offered from public.user_icons where user_id=tr.requester_id and icon_id=tr.offered_icon_id for update;
    select * into requested from public.user_icons where user_id=tr.receiver_id and icon_id=tr.requested_icon_id for update;
    if offered.icon_id is null or requested.icon_id is null then raise exception 'One of the icons is no longer owned.'; end if;
    delete from public.user_icons where user_id=tr.requester_id and icon_id=tr.offered_icon_id;
    delete from public.user_icons where user_id=tr.receiver_id and icon_id=tr.requested_icon_id;
    insert into public.user_icons(user_id, icon_id, icon, name, rarity) values(tr.receiver_id, offered.icon_id, offered.icon, offered.name, offered.rarity) on conflict do nothing;
    insert into public.user_icons(user_id, icon_id, icon, name, rarity) values(tr.requester_id, requested.icon_id, requested.icon, requested.name, requested.rarity) on conflict do nothing;
    update public.icon_trades set status='accepted', updated_at=now() where id=p_trade_id; return;
  else raise exception 'Bad trade response.';
  end if;
end; $$;
grant execute on function public.answer_icon_trade_v83(bigint, text) to authenticated;

-- Admin panel functions.
create or replace function public.admin_change_username_v83(p_old_username text, p_new_username text)
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid;
begin
 if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
 if p_new_username !~ '^[A-Za-z0-9_]{3,20}$' then raise exception 'Invalid username.'; end if;
 select id into target_id from public.profiles where lower(username)=lower(trim(p_old_username));
 if target_id is null then raise exception 'User not found.'; end if;
 update public.profiles set username=trim(p_new_username), username_changed_at=now() where id=target_id;
end; $$;
grant execute on function public.admin_change_username_v83(text,text) to authenticated;

create or replace function public.admin_adjust_points_v83(p_username text, p_points integer, p_reason text default '')
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid; amount integer:=coalesce(p_points,0);
begin
 if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
 select id into target_id from public.profiles where lower(username)=lower(trim(p_username));
 if target_id is null then raise exception 'User not found.'; end if;
 update public.profiles set points=greatest(0, coalesce(points,0)+amount) where id=target_id;
end; $$;
grant execute on function public.admin_adjust_points_v83(text,integer,text) to authenticated;

create or replace function public.admin_delete_user_by_username_v83(p_username text)
returns void language plpgsql security definer set search_path=public, auth as $$
declare target_id uuid;
begin
 if not public.is_blank_space_admin() then raise exception 'Admin only.'; end if;
 select id into target_id from public.profiles where lower(username)=lower(trim(p_username));
 if target_id is null then raise exception 'User not found.'; end if;
 perform public.delete_rows_for_account_if_column_exists_v2('admin_users', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('suggestions', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('game_stats', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('user_achievements', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('user_icons', 'user_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('friend_messages', 'sender_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('friends', 'requester_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('friends', 'receiver_id', target_id);
 perform public.delete_rows_for_account_if_column_exists_v2('profiles', 'id', target_id);
 delete from auth.users where id=target_id;
end; $$;
grant execute on function public.admin_delete_user_by_username_v83(text) to authenticated;

-- Leaderboard function remains compatible.
drop function if exists public.get_public_leaderboard(integer);
create function public.get_public_leaderboard(max_rows integer default 100)
returns table (id uuid, username text, avatar_url text, points integer, equipped_icon text)
language sql security definer set search_path=public as $$
  select p.id, p.username, p.avatar_url, p.points, p.equipped_icon
  from public.profiles p
  where not exists (select 1 from public.admin_users a where a.user_id = p.id)
  order by p.points desc, lower(p.username) asc
  limit greatest(1, least(coalesce(max_rows,100),100));
$$;
grant execute on function public.get_public_leaderboard(integer) to anon, authenticated;

select pg_notify('pgrst', 'reload schema');
