-- Blank Space v74 Supabase update
-- Run this in Supabase SQL Editor after the v73 setup.
-- Adds public approved suggestion viewing, denied suggestion status, friends/friend requests,
-- and keeps your existing profiles/suggestions data.

-- Suggestion status: switch from rejected to denied in the UI/database.
alter table public.suggestions drop constraint if exists suggestion_status_check;
update public.suggestions set status = 'denied' where status = 'rejected';
alter table public.suggestions
  add constraint suggestion_status_check check (status in ('pending', 'approved', 'denied', 'rejected'));

-- Let public visitors read profile usernames and approved suggestions, but not private account data.
drop policy if exists "profiles_select_all" on public.profiles;
drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles
for select
to anon, authenticated
using (true);

drop policy if exists "suggestions_select_approved_or_own_or_admin" on public.suggestions;
drop policy if exists "suggestions_select_public_or_own_or_admin" on public.suggestions;
create policy "suggestions_select_public_or_own_or_admin"
on public.suggestions
for select
to anon, authenticated
using (
  status = 'approved'
  or user_id = auth.uid()
  or public.is_blank_space_admin()
);

-- Friends table: one row can be a pending request or an accepted friendship.
create table if not exists public.friends (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint friends_no_self check (requester_id <> receiver_id),
  constraint friends_status_check check (status in ('pending', 'accepted', 'declined'))
);

create unique index if not exists friends_one_connection_per_pair
on public.friends ((least(requester_id, receiver_id)), (greatest(requester_id, receiver_id)));

alter table public.friends enable row level security;

drop trigger if exists friends_set_updated_at on public.friends;
create trigger friends_set_updated_at
before update on public.friends
for each row
execute function public.set_updated_at();

drop policy if exists "friends_select_own" on public.friends;
drop policy if exists "friends_insert_own_pending" on public.friends;
drop policy if exists "friends_update_receiver_response" on public.friends;
drop policy if exists "friends_delete_own" on public.friends;

create policy "friends_select_own"
on public.friends
for select
to authenticated
using (requester_id = auth.uid() or receiver_id = auth.uid());

create policy "friends_insert_own_pending"
on public.friends
for insert
to authenticated
with check (requester_id = auth.uid() and status = 'pending');

create policy "friends_update_receiver_response"
on public.friends
for update
to authenticated
using (receiver_id = auth.uid() and status = 'pending')
with check (receiver_id = auth.uid() and status in ('accepted', 'declined'));

create policy "friends_delete_own"
on public.friends
for delete
to authenticated
using (requester_id = auth.uid() or receiver_id = auth.uid());

-- To make yourself admin after creating your account, replace USER_ID_HERE with your User ID:
-- insert into public.admin_users (user_id) values ('USER_ID_HERE') on conflict (user_id) do nothing;
