-- Blank Space v101: Owner Chat View + Daily Rewards + Achievement Search backend fix
-- Paste this whole file into Supabase SQL Editor and click Run.
--
-- Fixes backend for:
-- 1) Owner Panel chat viewer:
--      owner_get_user_chat_view_v95(username, limit)
--      owner_get_user_chat_view_v99(username, limit)
--
-- 2) Daily Rewards:
--      get_daily_reward_status_v99()
--      claim_daily_reward_v99()
--      refresh_daily_reward_v99()
--
-- 3) Achievement Search:
--      search_achievements_v99(search_text, game_filter, locked_filter, limit)
--
-- Important:
-- - Supabase can fix the backend functions.
-- - A visible Refresh button and a broken visual search input are website-code issues.
-- - This SQL gives the website working backend functions to call, but if the buttons/input still do not appear
--   or do not call these functions, that requires a GitHub ZIP update.

-- ============================================================
-- 1) Required tables/columns
-- ============================================================

alter table public.profiles add column if not exists points integer default 0;
alter table public.profiles add column if not exists rank text default 'member';
alter table public.profiles add column if not exists username text;

update public.profiles
set points = 0
where points is null;

update public.profiles
set rank = 'member'
where rank is null or trim(rank) = '';

create table if not exists public.achievement_catalog (
  achievement_id text,
  title text,
  description text,
  icon text,
  game_title text,
  stat text,
  target integer,
  reward_points integer,
  difficulty text
);

alter table public.achievement_catalog add column if not exists achievement_id text;
alter table public.achievement_catalog add column if not exists title text;
alter table public.achievement_catalog add column if not exists description text;
alter table public.achievement_catalog add column if not exists icon text;
alter table public.achievement_catalog add column if not exists game_title text;
alter table public.achievement_catalog add column if not exists stat text;
alter table public.achievement_catalog add column if not exists target integer;
alter table public.achievement_catalog add column if not exists reward_points integer default 0;
alter table public.achievement_catalog add column if not exists difficulty text default 'medium';

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id text not null,
  title text default 'Achievement',
  description text default '',
  icon text default '🏆',
  game_title text,
  reward_points integer default 0,
  earned_at timestamptz default now()
);

alter table public.user_achievements add column if not exists title text default 'Achievement';
alter table public.user_achievements add column if not exists description text default '';
alter table public.user_achievements add column if not exists icon text default '🏆';
alter table public.user_achievements add column if not exists game_title text;
alter table public.user_achievements add column if not exists reward_points integer default 0;
alter table public.user_achievements add column if not exists earned_at timestamptz default now();

create unique index if not exists user_achievements_user_achievement_unique
on public.user_achievements(user_id, achievement_id);

create index if not exists achievement_catalog_search_idx
on public.achievement_catalog using gin (
  to_tsvector(
    'english',
    coalesce(title, '') || ' ' ||
    coalesce(description, '') || ' ' ||
    coalesce(game_title, '') || ' ' ||
    coalesce(difficulty, '') || ' ' ||
    coalesce(stat, '')
  )
);

-- Friend chat tables.
create table if not exists public.friends (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  friendship_id bigint not null references public.friends(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text,
  image_url text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.friend_messages add column if not exists body text;
alter table public.friend_messages add column if not exists image_url text;
alter table public.friend_messages add column if not exists read_at timestamptz;
alter table public.friend_messages add column if not exists created_at timestamptz default now();

-- Group chat tables.
create table if not exists public.group_chats (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_chat_members (
  group_id bigint not null references public.group_chats(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member',
  invited_by uuid references public.profiles(id) on delete set null,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.group_chat_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.group_chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.group_chat_messages add column if not exists body text;
alter table public.group_chat_messages add column if not exists image_url text;
alter table public.group_chat_messages add column if not exists created_at timestamptz default now();

create index if not exists friends_requester_idx on public.friends(requester_id);
create index if not exists friends_receiver_idx on public.friends(receiver_id);
create index if not exists friend_messages_friendship_created_idx on public.friend_messages(friendship_id, created_at desc);
create index if not exists group_chat_members_user_idx on public.group_chat_members(user_id);
create index if not exists group_chat_messages_group_created_idx on public.group_chat_messages(group_id, created_at desc);

-- Daily reward table.
create table if not exists public.daily_rewards (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  streak_day integer not null default 0,
  last_claim_date date,
  reset_wait_until date,
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 2) Owner/admin helpers
-- ============================================================

create or replace function public.is_blank_space_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and (
        lower(trim(coalesce(p.rank, 'member'))) = 'owner'
        or lower(trim(coalesce(p.username, ''))) in ('owner', 'admin')
      )
  );
$$;

grant execute on function public.is_blank_space_owner() to anon, authenticated;

create or replace function public.is_blank_space_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and (
        lower(trim(coalesce(p.rank, 'member'))) in ('owner', 'admin')
        or lower(trim(coalesce(p.username, ''))) in ('owner', 'admin')
      )
  );
$$;

grant execute on function public.is_blank_space_admin() to anon, authenticated;

-- ============================================================
-- 3) Owner chat viewer functions
-- ============================================================

drop function if exists public.owner_get_user_chat_view_v95(text, integer);
drop function if exists public.owner_get_user_chat_view_v99(text, integer);

create function public.owner_get_user_chat_view_v95(
  p_username text,
  p_limit integer default 250
)
returns table(
  chat_type text,
  chat_name text,
  sender_username text,
  is_target_sender boolean,
  body text,
  image_url text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target uuid;
  v_limit integer := greatest(1, least(coalesce(p_limit, 250), 500));
begin
  if auth.uid() is null then
    raise exception 'Sign in first.';
  end if;

  if not public.is_blank_space_owner() then
    raise exception 'Owner only.';
  end if;

  select p.id
  into v_target
  from public.profiles p
  where lower(trim(p.username)) = lower(trim(coalesce(p_username, '')))
  order by p.created_at asc nulls last, p.id asc
  limit 1;

  if v_target is null then
    raise exception 'User not found.';
  end if;

  return query
  with friend_rows as (
    select
      'friend'::text as chat_type,
      (
        '@' ||
        coalesce(
          case
            when f.requester_id = v_target then receiver_profile.username
            else requester_profile.username
          end,
          'friend'
        )
      )::text as chat_name,
      coalesce(sender_profile.username, 'Unknown')::text as sender_username,
      (fm.sender_id = v_target)::boolean as is_target_sender,
      coalesce(fm.body, '')::text as body,
      fm.image_url::text as image_url,
      fm.created_at::timestamptz as created_at
    from public.friend_messages fm
    join public.friends f on f.id = fm.friendship_id
    left join public.profiles sender_profile on sender_profile.id = fm.sender_id
    left join public.profiles receiver_profile on receiver_profile.id = f.receiver_id
    left join public.profiles requester_profile on requester_profile.id = f.requester_id
    where (f.requester_id = v_target or f.receiver_id = v_target)
      and coalesce(f.status, 'accepted') = 'accepted'
  ),
  group_rows as (
    select
      'group'::text as chat_type,
      coalesce(gc.name, 'Group Chat')::text as chat_name,
      coalesce(sender_profile.username, 'Unknown')::text as sender_username,
      (gm.sender_id = v_target)::boolean as is_target_sender,
      coalesce(gm.body, '')::text as body,
      gm.image_url::text as image_url,
      gm.created_at::timestamptz as created_at
    from public.group_chat_messages gm
    join public.group_chat_members gcm
      on gcm.group_id = gm.group_id
     and gcm.user_id = v_target
    join public.group_chats gc on gc.id = gm.group_id
    left join public.profiles sender_profile on sender_profile.id = gm.sender_id
  )
  select *
  from (
    select * from friend_rows
    union all
    select * from group_rows
  ) all_rows
  order by all_rows.created_at desc
  limit v_limit;
end;
$$;

grant execute on function public.owner_get_user_chat_view_v95(text, integer) to authenticated;

create function public.owner_get_user_chat_view_v99(
  p_username text,
  p_limit integer default 250
)
returns table(
  chat_type text,
  chat_name text,
  sender_username text,
  is_target_sender boolean,
  body text,
  image_url text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select *
  from public.owner_get_user_chat_view_v95(p_username, p_limit);
$$;

grant execute on function public.owner_get_user_chat_view_v99(text, integer) to authenticated;

-- ============================================================
-- 4) Daily reward backend functions
-- ============================================================

drop function if exists public.get_daily_reward_status_v99();

create function public.get_daily_reward_status_v99()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  r public.daily_rewards%rowtype;
  v_next integer := 1;
  v_can boolean := true;
  v_msg text := 'Ready.';
begin
  if v_uid is null then
    return jsonb_build_object(
      'ok', false,
      'signed_in', false,
      'can_claim', false,
      'next_day', 1,
      'message', 'Not signed in. Sign in on Account, then press Refresh on Daily Rewards.'
    );
  end if;

  select * into r from public.daily_rewards where user_id = v_uid;

  if r.user_id is null then
    return jsonb_build_object(
      'ok', true,
      'signed_in', true,
      'can_claim', true,
      'next_day', 1,
      'message', 'Ready for Day 1.',
      'streak_day', 0
    );
  end if;

  if r.last_claim_date = current_date then
    v_can := false;
    v_next := least(coalesce(r.streak_day, 0) + 1, 7);
    v_msg := 'Already claimed today.';
  elsif r.reset_wait_until is not null and current_date < r.reset_wait_until then
    v_can := false;
    v_next := 1;
    v_msg := 'You missed a day. Come back tomorrow to restart.';
  elsif r.last_claim_date is not null
        and r.last_claim_date < current_date - 1
        and r.reset_wait_until is null then
    v_can := false;
    v_next := 1;
    v_msg := 'You missed a day. Come back tomorrow to restart.';
  elsif r.last_claim_date = current_date - 1 then
    v_next := least(coalesce(r.streak_day, 0) + 1, 7);
  else
    v_next := 1;
  end if;

  return jsonb_build_object(
    'ok', true,
    'signed_in', true,
    'can_claim', v_can,
    'next_day', v_next,
    'message', v_msg,
    'streak_day', coalesce(r.streak_day, 0),
    'last_claim_date', r.last_claim_date,
    'reset_wait_until', r.reset_wait_until
  );
end;
$$;

grant execute on function public.get_daily_reward_status_v99() to anon, authenticated;

drop function if exists public.claim_daily_reward_v99();

create function public.claim_daily_reward_v99()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  r public.daily_rewards%rowtype;
  v_day integer := 1;
  v_points integer := 1;
begin
  if v_uid is null then
    return jsonb_build_object(
      'ok', false,
      'signed_in', false,
      'message', 'Not signed in. Sign in on Account, then press Refresh on Daily Rewards.'
    );
  end if;

  select * into r
  from public.daily_rewards
  where user_id = v_uid
  for update;

  if r.user_id is not null then
    if r.last_claim_date = current_date then
      return jsonb_build_object('ok', false, 'signed_in', true, 'message', 'Already claimed today.', 'day', r.streak_day);
    end if;

    if r.reset_wait_until is not null and current_date < r.reset_wait_until then
      return jsonb_build_object('ok', false, 'signed_in', true, 'message', 'You missed a day. Come back tomorrow to restart.');
    end if;

    if r.last_claim_date is not null
       and r.last_claim_date < current_date - 1
       and (r.reset_wait_until is null or r.reset_wait_until < current_date) then
      update public.daily_rewards
      set streak_day = 0,
          reset_wait_until = current_date + 1,
          updated_at = now()
      where user_id = v_uid;

      return jsonb_build_object('ok', false, 'signed_in', true, 'message', 'You missed a day. Come back tomorrow to restart at Day 1.');
    end if;

    if r.last_claim_date = current_date - 1 then
      v_day := least(coalesce(r.streak_day, 0) + 1, 7);
    else
      v_day := 1;
    end if;
  end if;

  v_points := case v_day
    when 1 then 1
    when 2 then 2
    when 3 then 3
    when 4 then 4
    when 5 then 5
    when 6 then 8
    else 10
  end;

  insert into public.daily_rewards(user_id, streak_day, last_claim_date, reset_wait_until, updated_at)
  values(v_uid, v_day, current_date, null, now())
  on conflict(user_id) do update set
    streak_day = excluded.streak_day,
    last_claim_date = excluded.last_claim_date,
    reset_wait_until = null,
    updated_at = now();

  perform set_config('blank_space.allow_points_update', '1', true);

  update public.profiles
  set points = coalesce(points, 0) + v_points
  where id = v_uid;

  return jsonb_build_object(
    'ok', true,
    'signed_in', true,
    'day', v_day,
    'points_awarded', v_points,
    'message', 'Claimed Day ' || v_day || ' for ' || v_points || ' point(s).'
  );
end;
$$;

grant execute on function public.claim_daily_reward_v99() to anon, authenticated;

drop function if exists public.refresh_daily_reward_v99();

create function public.refresh_daily_reward_v99()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select public.get_daily_reward_status_v99();
$$;

grant execute on function public.refresh_daily_reward_v99() to anon, authenticated;

-- ============================================================
-- 5) Achievement search backend function
-- ============================================================

drop function if exists public.search_achievements_v99(text, text, text, integer);

create function public.search_achievements_v99(
  p_search text default '',
  p_game_title text default null,
  p_locked_filter text default 'all',
  p_limit integer default 250
)
returns table(
  achievement_id text,
  title text,
  description text,
  icon text,
  game_title text,
  stat text,
  target integer,
  reward_points integer,
  difficulty text,
  unlocked boolean,
  earned_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_search text := lower(trim(coalesce(p_search, '')));
  v_game text := nullif(trim(coalesce(p_game_title, '')), '');
  v_filter text := lower(trim(coalesce(p_locked_filter, 'all')));
  v_limit integer := greatest(1, least(coalesce(p_limit, 250), 500));
begin
  if v_uid is null then
    raise exception 'Sign in first.';
  end if;

  return query
  select
    c.achievement_id,
    coalesce(c.title, 'Achievement') as title,
    coalesce(c.description, '') as description,
    coalesce(c.icon, '🏆') as icon,
    c.game_title,
    c.stat,
    c.target,
    greatest(0, coalesce(c.reward_points, 0)) as reward_points,
    coalesce(c.difficulty, 'medium') as difficulty,
    (ua.achievement_id is not null) as unlocked,
    ua.earned_at
  from public.achievement_catalog c
  left join public.user_achievements ua
    on ua.user_id = v_uid
   and ua.achievement_id = c.achievement_id
  where c.achievement_id is not null
    and (v_game is null or c.game_title = v_game)
    and (
      v_search = ''
      or lower(coalesce(c.title, '')) like '%' || v_search || '%'
      or lower(coalesce(c.description, '')) like '%' || v_search || '%'
      or lower(coalesce(c.game_title, '')) like '%' || v_search || '%'
      or lower(coalesce(c.difficulty, '')) like '%' || v_search || '%'
      or lower(coalesce(c.stat, '')) like '%' || v_search || '%'
      or lower(coalesce(c.achievement_id, '')) like '%' || v_search || '%'
    )
    and (
      v_filter = 'all'
      or (v_filter in ('unlocked', 'earned') and ua.achievement_id is not null)
      or (v_filter in ('locked', 'missing') and ua.achievement_id is null)
    )
  order by
    c.game_title,
    c.target nulls last,
    c.title
  limit v_limit;
end;
$$;

grant execute on function public.search_achievements_v99(text, text, text, integer) to authenticated;

-- ============================================================
-- 6) Health check
-- ============================================================

drop function if exists public.blank_space_chat_daily_search_fix_healthcheck();

create function public.blank_space_chat_daily_search_fix_healthcheck()
returns table(check_name text, result text)
language sql
security definer
set search_path = public
as $$
  select 'owner_chat_v95_function',
         case when to_regprocedure('public.owner_get_user_chat_view_v95(text, integer)') is not null then 'installed' else 'missing' end

  union all

  select 'owner_chat_v99_function',
         case when to_regprocedure('public.owner_get_user_chat_view_v99(text, integer)') is not null then 'installed' else 'missing' end

  union all

  select 'daily_status_function',
         case when to_regprocedure('public.get_daily_reward_status_v99()') is not null then 'installed' else 'missing' end

  union all

  select 'daily_claim_function',
         case when to_regprocedure('public.claim_daily_reward_v99()') is not null then 'installed' else 'missing' end

  union all

  select 'daily_refresh_function',
         case when to_regprocedure('public.refresh_daily_reward_v99()') is not null then 'installed' else 'missing' end

  union all

  select 'achievement_search_function',
         case when to_regprocedure('public.search_achievements_v99(text, text, text, integer)') is not null then 'installed' else 'missing' end

  union all

  select 'status',
         'OK - Blank Space v101 chat view, daily rewards, and achievement search backend fixed';
$$;

grant execute on function public.blank_space_chat_daily_search_fix_healthcheck() to anon, authenticated;

select pg_notify('pgrst', 'reload schema');

select * from public.blank_space_chat_daily_search_fix_healthcheck();

-- Done.
